In [1]:
import tensorflow as tf
# import tensorflow_hub as hub
# from tensorflow_docs.vis import embed
import numpy as np
import cv2

# # Import matplotlib libraries
# from matplotlib import pyplot as plt
# from matplotlib.collections import LineCollection
# import matplotlib.patches as patches

# # Some modules to display an animation using imageio.
# import imageio
# from IPython.display import HTML, display

In [2]:
 # Initialize the TFLite interpreter
interpreter = tf.lite.Interpreter(model_path="/Users/jusuklee/Desktop/2022-2/movenet/lite-model_movenet_singlepose_lightning_3.tflite")
interpreter.allocate_tensors()

In [6]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Reshape image
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img, axis=0), 192,192)
    input_image = tf.cast(img, dtype=tf.float32)
    
    # Setup input and output 
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    # Make predictions 
    interpreter.set_tensor(input_details[0]['index'], np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    print(keypoints_with_scores)
    # Rendering 
    draw_connections(frame, keypoints_with_scores, EDGES, 0.4)
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    
    cv2.imshow('MoveNet Lightning', frame)
        
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
cap.release()
# cv2.destroyAllwindows()

[ WARN:0@16.869] global /private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_562_cazh1h/croots/recipe/opencv-suite_1664548333142/work/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
2022-11-01 09:19:33.102879: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-11-01 09:19:33.103049: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1
[[[[0.3871165  0.5281175  0.6572946 ]
   [0.337017   0.5795264  0.6419341 ]
   [0.3309906  0.4780463  0.5934211 ]
   [0.38291305 0.64852047 0.5155698 ]
   [0.37685582 0.41639575 0.6182544 ]
   [0.58122265 0.7627392  0.60615975]
   [0.6092632  0.31294084 0.83345383]
   [0.7519932  0.91696584 0.18210177]
   [0.7618462  0.24555811 0.01436165]
   [0.6958618  0.80958223 0.02472914]
   [0.6481614  0.40822023 0.00558195]
   [0.841017   0.89900935 0.02547404]
   [0.31935    0.7165431  0.0218373 ]
   [0.73964286 0.866872   0.02104563]
   [0.58897483 0.3062532  0.01976079]
   [0.7475674  0.74717665 0.0031203 ]
   [0.56336486 0.01531644 0.02640648]]]]
[[[[0.3796718  0.53025043 0.6524081 ]
   [0.3340993  0.58383805 0.50029045]
   [0.32961395 0.4812652  0.6657789 ]
   [0.38333368 0.64035136 0.66958   ]
   [0.37913787 0.41731617 0.69952357]
   [0.571135   0.7634276  0.6324495 ]
   [0.60398865 0.3093764  0.88308233]
   [0.76100844 0.8724312  0.04841043]
   [0.76680917 0.

[[[[0.38093865 0.4894905  0.6950925 ]
   [0.33089957 0.53535724 0.6536277 ]
   [0.33527777 0.44131166 0.59126693]
   [0.37544864 0.60051835 0.6530435 ]
   [0.3798812  0.38984233 0.5776141 ]
   [0.54685086 0.7377967  0.79766154]
   [0.6135341  0.27958193 0.9043051 ]
   [0.76928824 0.8664067  0.04880508]
   [0.7456074  0.22165874 0.01255354]
   [0.5807975  0.65456986 0.00824304]
   [0.49065492 0.0242369  0.03735426]
   [0.34082228 0.6833794  0.01188668]
   [0.29752925 0.6659467  0.01382235]
   [0.53222555 0.7599122  0.02308639]
   [0.60361826 0.28620315 0.02484615]
   [0.53626263 0.7372553  0.00520513]
   [0.5019773  0.02181528 0.0161074 ]]]]
[[[[0.38524407 0.4822672  0.620779  ]
   [0.33495963 0.5305809  0.51697665]
   [0.34054703 0.4312894  0.7103106 ]
   [0.38059244 0.5918681  0.76516515]
   [0.38553306 0.3805235  0.7693746 ]
   [0.5517571  0.7223622  0.60553986]
   [0.6195891  0.2732541  0.84114206]
   [0.7686151  0.85488117 0.12502274]
   [0.75738394 0.20334095 0.02585885]
   [0.621

[[[[0.37213677 0.12924962 0.27339396]
   [0.31180325 0.16556638 0.26758286]
   [0.30819562 0.09820317 0.19257495]
   [0.33064675 0.18555179 0.12244394]
   [0.32430422 0.06518528 0.16769846]
   [0.54854286 0.26654583 0.20183553]
   [0.4980366  0.04912291 0.05639469]
   [0.71585727 0.38159418 0.14005515]
   [0.75320166 0.17225729 0.08754049]
   [0.55012673 0.26750275 0.05207081]
   [0.50726146 0.1841899  0.04880142]
   [0.69368756 0.36260682 0.03715169]
   [0.6437899  0.24402249 0.03657381]
   [0.616712   0.3432506  0.03991989]
   [0.6010121  0.19966805 0.03354482]
   [0.59227824 0.29743955 0.01934195]
   [0.56417984 0.1731168  0.0189645 ]]]]
[[[[0.36646187 0.08162202 0.22765948]
   [0.32403147 0.10076617 0.21796098]
   [0.32406497 0.05627721 0.19894543]
   [0.32687938 0.12419237 0.2039238 ]
   [0.33862838 0.02192802 0.10883472]
   [0.53447944 0.2025722  0.24794509]
   [0.4926026  0.05358715 0.05357466]
   [0.7414001  0.3425425  0.12782991]
   [0.7643034  0.02519552 0.06457283]
   [0.547

[[[[ 0.4819277  -0.01047542  0.03872879]
   [ 0.25255978  0.02247087  0.07220202]
   [ 0.46950108 -0.01521969  0.03600598]
   [ 0.47329247 -0.0039103   0.08215299]
   [ 0.46005365 -0.0070818   0.06207254]
   [ 0.5366551   0.03803806  0.27340296]
   [ 0.5329268   0.0213028   0.2507147 ]
   [ 0.6287712   0.01933299  0.03391266]
   [ 0.5826522   0.02998624  0.05177908]
   [ 0.7529657   0.02096018  0.0482049 ]
   [ 0.7562108   0.02772881  0.06240472]
   [ 0.75394464  0.12825581  0.09788195]
   [ 0.7520835   0.12310643  0.08487035]
   [ 0.768378    0.01762264  0.0419547 ]
   [ 0.7704453   0.01675686  0.04698439]
   [ 0.7722738   0.02370515  0.03929597]
   [ 0.7657508   0.02103128  0.0380316 ]]]]
[[[[ 0.4695321  -0.0148751   0.03389318]
   [ 0.25621843  0.01663322  0.05817592]
   [ 0.45721185 -0.01884151  0.03030055]
   [ 0.4591523  -0.00673429  0.06396528]
   [ 0.45773637 -0.00890099  0.06122334]
   [ 0.5315242   0.02874577  0.27323   ]
   [ 0.5276357   0.02021082  0.27059647]
   [ 0.631986

[[[[0.52427036 0.7372315  0.31855032]
   [0.5013542  0.75549173 0.30366656]
   [0.5012647  0.7174685  0.3727592 ]
   [0.4903061  0.8108227  0.2853081 ]
   [0.4954431  0.7014789  0.3632195 ]
   [0.5691683  0.8270674  0.28851467]
   [0.5640224  0.7099986  0.29260093]
   [0.68335193 0.7795462  0.15373932]
   [0.6580719  0.6684538  0.1344403 ]
   [0.69576204 0.6994729  0.11237611]
   [0.7220515  0.6534477  0.14556013]
   [0.70771444 0.7879943  0.19313772]
   [0.7065684  0.733827   0.1845118 ]
   [0.7316999  0.7361259  0.1694567 ]
   [0.737605   0.6847303  0.16400161]
   [0.73526895 0.67924356 0.06703594]
   [0.73684496 0.65122706 0.07741682]]]]
[[[[0.5228151  0.71773237 0.44220546]
   [0.48957872 0.74690264 0.52135736]
   [0.4935376  0.69344926 0.40501067]
   [0.49175414 0.81575584 0.47174603]
   [0.49721643 0.67987907 0.32454547]
   [0.59930694 0.8441634  0.2972249 ]
   [0.5857471  0.6725242  0.3975969 ]
   [0.733755   0.80767524 0.26892972]
   [0.706525   0.6467968  0.27818775]
   [0.686

[[[[0.5390575  0.7177891  0.36797148]
   [0.5009501  0.7318112  0.26080078]
   [0.498523   0.69424814 0.46370822]
   [0.5072987  0.814868   0.33900067]
   [0.49494874 0.6969377  0.38023537]
   [0.6231242  0.8201448  0.23149806]
   [0.5900799  0.6802876  0.3497625 ]
   [0.7219012  0.7408318  0.18280685]
   [0.71963644 0.641503   0.20930758]
   [0.6782782  0.65251637 0.0837443 ]
   [0.7252831  0.60358787 0.2253158 ]
   [0.7581615  0.75616634 0.12018805]
   [0.75035536 0.6778257  0.1492941 ]
   [0.7382183  0.67678225 0.17537676]
   [0.7153419  0.5713915  0.07573132]
   [0.735139   0.59829235 0.10284171]
   [0.7193775  0.5380362  0.07552518]]]]
[[[[0.52674043 0.72250676 0.50219536]
   [0.48715597 0.7512301  0.44928446]
   [0.4954495  0.6915983  0.38126796]
   [0.48290193 0.8201996  0.46084455]
   [0.49979907 0.67265695 0.36353308]
   [0.59875435 0.9329964  0.56330556]
   [0.59674346 0.6523624  0.678426  ]
   [0.7675583  0.95857525 0.18764547]
   [0.74078107 0.65002406 0.39138788]
   [0.754

[[[[0.5437167  0.5676595  0.3251897 ]
   [0.5030262  0.5977323  0.28160894]
   [0.51004755 0.54261786 0.50269073]
   [0.4973426  0.6659113  0.42167062]
   [0.50728315 0.53886735 0.49152574]
   [0.59437025 0.76925755 0.7467399 ]
   [0.5892411  0.49007398 0.8277316 ]
   [0.76453936 0.82567954 0.13007727]
   [0.75130785 0.5024464  0.5663467 ]
   [0.7651844  0.6619673  0.20120999]
   [0.75120276 0.5794525  0.13242762]
   [0.826894   0.7214514  0.04876118]
   [0.81172097 0.57538235 0.1409907 ]
   [0.7544281  0.67070264 0.05732911]
   [0.7357485  0.5271535  0.17785452]
   [0.7672097  0.66866016 0.02384942]
   [0.75708264 0.64129615 0.06271837]]]]
[[[[0.5238356  0.5790913  0.38638005]
   [0.48594218 0.6126093  0.52996606]
   [0.4945384  0.55447054 0.59808797]
   [0.48989162 0.6692931  0.5542195 ]
   [0.4989689  0.53994566 0.3988304 ]
   [0.5941333  0.75783134 0.7130635 ]
   [0.58892983 0.49844313 0.76436794]
   [0.76024246 0.814235   0.41947216]
   [0.74554324 0.5025003  0.44724497]
   [0.767

[[[[0.46294042 0.6060295  0.5557741 ]
   [0.43406138 0.6416766  0.49701062]
   [0.43063468 0.5900558  0.67361057]
   [0.44592106 0.71311903 0.68907624]
   [0.4268237  0.590427   0.51011497]
   [0.54022133 0.78694904 0.6693678 ]
   [0.5381021  0.51378673 0.86817294]
   [0.73667324 0.8228027  0.3946597 ]
   [0.6948301  0.5054891  0.39975566]
   [0.75433964 0.7584957  0.15220803]
   [0.6940622  0.6449691  0.20987773]
   [0.80669475 0.68840504 0.10369663]
   [0.7984495  0.56697273 0.09873679]
   [0.7245097  0.71910375 0.03445473]
   [0.6936228  0.51557463 0.19745263]
   [0.73636043 0.68672174 0.02871413]
   [0.73298967 0.68760574 0.06659426]]]]
[[[[0.45930204 0.6160837  0.39603972]
   [0.4235464  0.65522474 0.43761036]
   [0.42071804 0.60016763 0.4297071 ]
   [0.4273736  0.71774626 0.68308455]
   [0.41529307 0.5938495  0.48025087]
   [0.5206199  0.79610175 0.7074017 ]
   [0.52285874 0.51493    0.6894047 ]
   [0.7296537  0.8317644  0.41878402]
   [0.7015568  0.48459095 0.53377223]
   [0.751

[[[[0.43017957 0.64455396 0.51400447]
   [0.4036461  0.67678535 0.44114256]
   [0.3990727  0.62442315 0.5015744 ]
   [0.41384614 0.7350027  0.6858711 ]
   [0.39825165 0.6139201  0.4710786 ]
   [0.5333139  0.80911684 0.6479238 ]
   [0.51871336 0.53906804 0.74244267]
   [0.7288631  0.84267557 0.3764803 ]
   [0.6884355  0.49767995 0.56477904]
   [0.7439337  0.74070823 0.28965187]
   [0.6973953  0.5600238  0.15070677]
   [0.8179501  0.73014605 0.10152371]
   [0.812704   0.5947373  0.10768389]
   [0.72739404 0.78588    0.03231471]
   [0.67537653 0.5116577  0.19598527]
   [0.73027265 0.60229766 0.07498461]
   [0.7364528  0.7071445  0.04989485]]]]
[[[[0.43417323 0.6385578  0.42590144]
   [0.40738428 0.6720228  0.4019398 ]
   [0.40397045 0.6216148  0.42960644]
   [0.41790897 0.73449826 0.5174513 ]
   [0.40006444 0.6173897  0.528863  ]
   [0.5337418  0.8152558  0.733499  ]
   [0.52096194 0.5338053  0.6863359 ]
   [0.7307526  0.84049726 0.41637284]
   [0.68728626 0.4931807  0.4990556 ]
   [0.747

[[[[0.43624455 0.6537561  0.5385662 ]
   [0.40482005 0.6860137  0.49175116]
   [0.40487    0.6309255  0.58749026]
   [0.4164256  0.7340548  0.57660526]
   [0.4068432  0.61149377 0.72812724]
   [0.5416193  0.81721157 0.76445186]
   [0.52528745 0.5332105  0.8392543 ]
   [0.72099113 0.859316   0.3213531 ]
   [0.70525455 0.48141694 0.3994754 ]
   [0.7480337  0.79401445 0.53134334]
   [0.73067707 0.5358087  0.17061056]
   [0.8606798  0.73394644 0.04224442]
   [0.8475418  0.5701961  0.03106944]
   [0.7444491  0.85415256 0.035965  ]
   [0.7125014  0.501716   0.13055044]
   [0.7550873  0.60677844 0.01697132]
   [0.7468748  0.58854616 0.04262668]]]]
[[[[0.43688545 0.6527113  0.5262773 ]
   [0.40476793 0.68509233 0.49456933]
   [0.40571794 0.63057643 0.61410356]
   [0.41594395 0.7343831  0.5709326 ]
   [0.40796    0.6127105  0.7567749 ]
   [0.54060656 0.8202714  0.76150435]
   [0.52602506 0.5304699  0.84547776]
   [0.71434927 0.8623357  0.29621562]
   [0.6977433  0.48953468 0.49365652]
   [0.743

[[[[0.43520248 0.6315006  0.4705398 ]
   [0.40631348 0.66520846 0.40944284]
   [0.403306   0.6151147  0.66570026]
   [0.42025158 0.7287017  0.6062914 ]
   [0.40832353 0.61086875 0.57724106]
   [0.54087317 0.81574416 0.69901043]
   [0.5276941  0.5330223  0.8607367 ]
   [0.73063517 0.8503219  0.492141  ]
   [0.700365   0.47842258 0.3643564 ]
   [0.74957514 0.74209136 0.38695934]
   [0.72418284 0.55185485 0.1618828 ]
   [0.855863   0.73203635 0.05769279]
   [0.84308195 0.5760827  0.03916693]
   [0.7551056  0.7631039  0.01935848]
   [0.7067995  0.49632928 0.16164033]
   [0.7472862  0.6106807  0.0538406 ]
   [0.7374915  0.59717077 0.04879995]]]]
[[[[0.43668175 0.62944895 0.41997665]
   [0.40746015 0.6613459  0.5316306 ]
   [0.4057219  0.6135271  0.6887727 ]
   [0.42046845 0.7271998  0.62114656]
   [0.40961158 0.612833   0.59824693]
   [0.53987765 0.8162576  0.67964643]
   [0.5276661  0.53505135 0.85044146]
   [0.7281083  0.85493207 0.47714671]
   [0.700016   0.4799454  0.3916437 ]
   [0.748

[[[[0.44212812 0.63893175 0.46404538]
   [0.41223562 0.67091846 0.6231645 ]
   [0.40972722 0.61934525 0.5083376 ]
   [0.42195863 0.73125976 0.62183005]
   [0.40873897 0.6111638  0.63191974]
   [0.5389582  0.816935   0.7541568 ]
   [0.5273415  0.5303586  0.8492509 ]
   [0.7258007  0.8554133  0.38602996]
   [0.7011397  0.48220974 0.43544585]
   [0.742483   0.7551834  0.3617702 ]
   [0.72238755 0.5493517  0.12293641]
   [0.8442483  0.74041975 0.06069094]
   [0.83698004 0.57917136 0.03598726]
   [0.74352515 0.8375764  0.0399798 ]
   [0.70731735 0.4982959  0.13718499]
   [0.74448484 0.6125634  0.02246826]
   [0.7358624  0.59581375 0.03343083]]]]
[[[[0.44284683 0.6393523  0.47910327]
   [0.41345972 0.6713017  0.6121909 ]
   [0.41056114 0.6195097  0.50357145]
   [0.4227218  0.73111916 0.62959546]
   [0.40910062 0.6106386  0.6190307 ]
   [0.53770816 0.8154546  0.7455225 ]
   [0.52856505 0.53152037 0.8448972 ]
   [0.72319067 0.85367596 0.3718229 ]
   [0.7029294  0.48139593 0.42067254]
   [0.741

[[[[0.44493222 0.6318932  0.4641925 ]
   [0.41535112 0.6629531  0.5000242 ]
   [0.41348538 0.6155254  0.5243402 ]
   [0.42319953 0.72498584 0.5979799 ]
   [0.4131891  0.61362463 0.61274415]
   [0.53762436 0.8165437  0.77917707]
   [0.5271558  0.5325504  0.8415637 ]
   [0.71400225 0.84898055 0.33023253]
   [0.69133395 0.47391722 0.526587  ]
   [0.73953164 0.75566834 0.36504513]
   [0.71874064 0.5330744  0.13009422]
   [0.84384173 0.7418512  0.07522631]
   [0.84204423 0.57660586 0.03631178]
   [0.74595875 0.8338444  0.03586579]
   [0.71517843 0.48359203 0.09536398]
   [0.7480392  0.58973867 0.01110955]
   [0.74286723 0.59302527 0.02276247]]]]
[[[[0.43994927 0.6395894  0.43405715]
   [0.4109102  0.6675184  0.47070622]
   [0.41144782 0.61950076 0.507069  ]
   [0.4216865  0.7241694  0.5657115 ]
   [0.4110572  0.61272067 0.60633975]
   [0.5389775  0.81480145 0.70041144]
   [0.5289527  0.53379476 0.6360442 ]
   [0.7139826  0.8375811  0.39111376]
   [0.69080067 0.47537145 0.5317621 ]
   [0.739

[[[[0.4386357  0.6304544  0.40199882]
   [0.40887797 0.65932155 0.58359534]
   [0.40858185 0.6149905  0.627075  ]
   [0.42239225 0.7238723  0.58691496]
   [0.41066357 0.6115131  0.5646631 ]
   [0.5400521  0.8168546  0.62828875]
   [0.53095293 0.53550684 0.80527693]
   [0.7219717  0.8404807  0.30409318]
   [0.6913068  0.4778344  0.49274838]
   [0.7436859  0.7472872  0.3746989 ]
   [0.72687024 0.50730324 0.21579617]
   [0.8388662  0.7432885  0.08560538]
   [0.84151363 0.58448917 0.03438615]
   [0.7568536  0.7630323  0.01934695]
   [0.72321576 0.48056743 0.06218222]
   [0.7544528  0.60237616 0.01712163]
   [0.74569345 0.58415836 0.02106712]]]]
[[[[0.43942186 0.63036144 0.3962395 ]
   [0.40919405 0.66040885 0.59040105]
   [0.40803403 0.6146635  0.64656126]
   [0.42213342 0.7243519  0.60589516]
   [0.41005847 0.61230254 0.58785665]
   [0.53995717 0.81582725 0.6646649 ]
   [0.52935195 0.5327586  0.8483866 ]
   [0.7231746  0.843222   0.40993756]
   [0.6983974  0.4825132  0.35744575]
   [0.744

[[[[0.44698688 0.64153266 0.39811373]
   [0.41875476 0.6729242  0.3587832 ]
   [0.41542944 0.62072957 0.5068131 ]
   [0.42265415 0.73114246 0.6180911 ]
   [0.40948707 0.60639846 0.56639564]
   [0.5415423  0.81425524 0.71383226]
   [0.5295801  0.5331981  0.83588517]
   [0.7284314  0.8473499  0.31787106]
   [0.70213175 0.4877182  0.49217424]
   [0.744033   0.7741842  0.43988797]
   [0.7359767  0.57769537 0.19032307]
   [0.8463203  0.7376162  0.06005479]
   [0.83953977 0.5731249  0.03067685]
   [0.7568381  0.7816765  0.01819589]
   [0.7157545  0.49743387 0.0972378 ]
   [0.7501197  0.6184972  0.00987665]
   [0.7419436  0.59920603 0.02581856]]]]
[[[[0.44125065 0.6391225  0.3449191 ]
   [0.41278297 0.67232126 0.5939833 ]
   [0.41110894 0.6200739  0.4726164 ]
   [0.420209   0.7308377  0.5772627 ]
   [0.40636295 0.60706997 0.516955  ]
   [0.5406373  0.81382215 0.65538806]
   [0.5292415  0.5333414  0.83066785]
   [0.72842836 0.84775233 0.36386132]
   [0.70090914 0.49072367 0.5223612 ]
   [0.748

[[[[0.43989608 0.64035016 0.3553599 ]
   [0.41125354 0.6744354  0.6563488 ]
   [0.41010278 0.6197382  0.538221  ]
   [0.42124984 0.73181736 0.6186541 ]
   [0.40792117 0.60546076 0.51797193]
   [0.5371964  0.81738436 0.7766901 ]
   [0.528803   0.5292043  0.8437266 ]
   [0.72741264 0.85588145 0.3587625 ]
   [0.6935989  0.49467206 0.51329225]
   [0.7448003  0.7720701  0.43232715]
   [0.7332244  0.5860553  0.1602886 ]
   [0.84296864 0.7339255  0.06963257]
   [0.83783334 0.5732994  0.03267265]
   [0.7427397  0.84068847 0.04625447]
   [0.71556634 0.5005633  0.09826776]
   [0.75248784 0.7435641  0.01268136]
   [0.7421353  0.6701442  0.01848407]]]]
[[[[0.43886292 0.63646823 0.41596636]
   [0.4099116  0.6667504  0.5985008 ]
   [0.4058867  0.61729777 0.64689386]
   [0.42105538 0.7291919  0.5718998 ]
   [0.4064301  0.6073365  0.5087281 ]
   [0.53889775 0.81674767 0.7541247 ]
   [0.5309705  0.5308319  0.8497187 ]
   [0.72943807 0.8537241  0.4031018 ]
   [0.69739646 0.49430084 0.5438167 ]
   [0.742

[[[[0.44673896 0.63438463 0.5084665 ]
   [0.41834566 0.66529566 0.35763353]
   [0.41379198 0.61656475 0.6269905 ]
   [0.4218731  0.72779906 0.5688668 ]
   [0.41215318 0.6112396  0.5966428 ]
   [0.5406327  0.8162873  0.6893444 ]
   [0.5308669  0.534312   0.83358324]
   [0.7266815  0.85500586 0.38345435]
   [0.69969976 0.48563263 0.4687093 ]
   [0.74493784 0.7567805  0.44472373]
   [0.72706056 0.5861442  0.1754044 ]
   [0.84813356 0.73511785 0.05677027]
   [0.8395753  0.57581615 0.03033411]
   [0.7549622  0.78290474 0.01720493]
   [0.70709723 0.4985984  0.12153243]
   [0.7417383  0.6169901  0.01842795]
   [0.7337917  0.60750157 0.02521897]]]]
[[[[0.4459433  0.63397884 0.4936515 ]
   [0.41799897 0.66537714 0.3606791 ]
   [0.4136842  0.616333   0.64140826]
   [0.42192507 0.7274506  0.5659573 ]
   [0.412688   0.61112046 0.5847033 ]
   [0.5404034  0.8171243  0.67726254]
   [0.5308345  0.5347387  0.8354145 ]
   [0.72512627 0.8554947  0.39154977]
   [0.6980979  0.4884865  0.49589473]
   [0.745

[[[[0.4429564  0.63715434 0.55651134]
   [0.4113387  0.66954315 0.47451556]
   [0.409656   0.61772645 0.6342674 ]
   [0.42238128 0.7303545  0.5668574 ]
   [0.41237935 0.6077875  0.5523762 ]
   [0.54185927 0.8169018  0.56352973]
   [0.5313232  0.53523207 0.8278224 ]
   [0.73022765 0.85378146 0.38541225]
   [0.70115554 0.48762116 0.5066687 ]
   [0.74490654 0.75069684 0.41224772]
   [0.73210955 0.59129953 0.1727186 ]
   [0.84696186 0.7347479  0.05860914]
   [0.8459251  0.57774496 0.03227837]
   [0.73772    0.8176577  0.02702063]
   [0.709515   0.502182   0.11230605]
   [0.7445593  0.6186216  0.02178347]
   [0.73703885 0.6104983  0.02191806]]]]
[[[[0.4423958  0.6312596  0.46395147]
   [0.41259068 0.66289395 0.534903  ]
   [0.41065794 0.61387026 0.64671135]
   [0.42107022 0.72527236 0.6083229 ]
   [0.41022646 0.60984623 0.5352435 ]
   [0.5392041  0.8120689  0.71588737]
   [0.5301165  0.534425   0.67713237]
   [0.7291137  0.8393121  0.35842833]
   [0.69930553 0.48459935 0.4254163 ]
   [0.744

[[[[0.44612396 0.6320157  0.509526  ]
   [0.4153908  0.665186   0.5088323 ]
   [0.41190487 0.6152045  0.63053894]
   [0.4211675  0.7262082  0.64044136]
   [0.41228136 0.61315143 0.621497  ]
   [0.54187936 0.8172802  0.7008507 ]
   [0.52951205 0.5316812  0.85782367]
   [0.73278445 0.858158   0.40941522]
   [0.7042773  0.48441225 0.4618455 ]
   [0.74691033 0.7564119  0.39229783]
   [0.7306279  0.5870892  0.16005157]
   [0.8575771  0.7313249  0.05296993]
   [0.8487372  0.57310224 0.02671137]
   [0.7379045  0.81846476 0.02719121]
   [0.7091688  0.4921083  0.09498737]
   [0.7427909  0.61556685 0.01806652]
   [0.73483515 0.6077154  0.02164523]]]]
[[[[0.4462758  0.63129544 0.49904305]
   [0.41554642 0.66372645 0.5136629 ]
   [0.41206354 0.6143637  0.6362396 ]
   [0.42178568 0.7252812  0.64954776]
   [0.41193467 0.61268914 0.6144305 ]
   [0.54204875 0.8176031  0.6978237 ]
   [0.52882427 0.5322429  0.8520839 ]
   [0.73113084 0.8546653  0.4096164 ]
   [0.7032756  0.4838297  0.43625277]
   [0.746

[[[[0.44257194 0.6289711  0.42890704]
   [0.41189885 0.6621605  0.5732497 ]
   [0.40983367 0.61189926 0.7096946 ]
   [0.4201902  0.7261569  0.62350607]
   [0.41168118 0.60880005 0.58045954]
   [0.54251325 0.8168253  0.7305542 ]
   [0.5314026  0.53207004 0.6857758 ]
   [0.7301845  0.85241103 0.41438955]
   [0.70599127 0.48442027 0.5004272 ]
   [0.74732673 0.7604023  0.3628236 ]
   [0.72944474 0.5895915  0.17166892]
   [0.861606   0.7355225  0.05562092]
   [0.8482553  0.57529926 0.03115894]
   [0.7437245  0.8375675  0.03186693]
   [0.7101509  0.50155747 0.11790886]
   [0.742445   0.6190301  0.01788021]
   [0.73702735 0.67423075 0.02129344]]]]
[[[[0.44103977 0.62679225 0.38300335]
   [0.41007861 0.6601441  0.5987642 ]
   [0.40790266 0.61067575 0.68018156]
   [0.41887456 0.725803   0.6056261 ]
   [0.40913212 0.6091977  0.5608115 ]
   [0.54179406 0.81588936 0.72963196]
   [0.53160065 0.53220576 0.6859062 ]
   [0.7304937  0.8472774  0.4024906 ]
   [0.70502245 0.48135626 0.44291613]
   [0.747

[[[[0.44589514 0.61061805 0.485725  ]
   [0.41283092 0.64382505 0.44174424]
   [0.4108315  0.59586495 0.45662934]
   [0.42155454 0.71719646 0.7130762 ]
   [0.41410398 0.60372233 0.481546  ]
   [0.5433613  0.81440204 0.6581056 ]
   [0.53185296 0.5356418  0.83045644]
   [0.73229825 0.8549222  0.41973785]
   [0.7009374  0.48627663 0.45466137]
   [0.74657416 0.74830794 0.38061184]
   [0.72177947 0.557219   0.11466418]
   [0.85875624 0.7316241  0.04877083]
   [0.8499936  0.5804165  0.02670412]
   [0.7535105  0.7448258  0.01203819]
   [0.7139434  0.487033   0.0959636 ]
   [0.7367506  0.5922704  0.01705647]
   [0.7384263  0.6030649  0.02434907]]]]
[[[[0.44635245 0.6142272  0.513126  ]
   [0.41395706 0.64477956 0.4322848 ]
   [0.41426098 0.59921885 0.5287582 ]
   [0.41692442 0.7171072  0.63133085]
   [0.41101238 0.60354567 0.5048722 ]
   [0.5385629  0.8148936  0.7135773 ]
   [0.53057945 0.53481334 0.7080175 ]
   [0.72332376 0.8488189  0.38058263]
   [0.69595265 0.48275626 0.40177968]
   [0.742

[[[[0.45920056 0.60025066 0.40128118]
   [0.418557   0.6339866  0.6201239 ]
   [0.42908654 0.5679087  0.724042  ]
   [0.42243028 0.692731   0.6251556 ]
   [0.439292   0.54090035 0.5897955 ]
   [0.50883317 0.7883081  0.85493666]
   [0.53356063 0.4991693  0.77774894]
   [0.72196615 0.8687364  0.4750577 ]
   [0.7008187  0.4681548  0.45824316]
   [0.7480907  0.7648852  0.3382691 ]
   [0.7187513  0.5049549  0.20118444]
   [0.8318135  0.7228857  0.12155696]
   [0.8304124  0.56128585 0.05978231]
   [0.7447319  0.84114766 0.02893033]
   [0.70828843 0.49109387 0.15486632]
   [0.7455152  0.62090075 0.01078325]
   [0.7363918  0.599508   0.03655295]]]]
[[[[0.46483183 0.57450676 0.5000518 ]
   [0.42706025 0.6136462  0.38691655]
   [0.43419492 0.55210817 0.63087326]
   [0.42467055 0.68644667 0.55088115]
   [0.43677756 0.55448383 0.4832391 ]
   [0.50819325 0.78365463 0.8159239 ]
   [0.5367016  0.50120556 0.8307228 ]
   [0.7235619  0.86765164 0.47520402]
   [0.7044283  0.47045702 0.4768951 ]
   [0.748

[[[[0.48365664 0.6251142  0.43011278]
   [0.44068092 0.6572528  0.4832887 ]
   [0.4476224  0.5845037  0.49216622]
   [0.4409214  0.6997938  0.5645352 ]
   [0.45464188 0.5348028  0.6082681 ]
   [0.51674026 0.780497   0.83537287]
   [0.54442513 0.48439175 0.8252212 ]
   [0.7208156  0.857073   0.3255091 ]
   [0.72057843 0.4712246  0.45791116]
   [0.750366   0.7834794  0.27459237]
   [0.72754    0.5011087  0.19557852]
   [0.8248507  0.7249559  0.08546548]
   [0.82387704 0.55864805 0.0787484 ]
   [0.7489613  0.86507577 0.03661843]
   [0.7119262  0.49642593 0.14170782]
   [0.7637228  0.8439888  0.01069919]
   [0.743664   0.59809583 0.01965579]]]]
[[[[0.48454866 0.6138595  0.5615681 ]
   [0.44188035 0.6511489  0.47235906]
   [0.4480388  0.5774965  0.67037255]
   [0.44327706 0.6992643  0.6240165 ]
   [0.45429343 0.53628653 0.6124497 ]
   [0.5144106  0.7816526  0.8423983 ]
   [0.54426044 0.4852528  0.835523  ]
   [0.73268366 0.8661765  0.23966497]
   [0.7316947  0.4693691  0.42383665]
   [0.755

[[[[0.46131513 0.60188985 0.4537027 ]
   [0.42458445 0.6394952  0.6679761 ]
   [0.42957467 0.5763999  0.75815123]
   [0.42704606 0.69434464 0.69106317]
   [0.435771   0.5504917  0.6122679 ]
   [0.50720537 0.789706   0.8513989 ]
   [0.53057975 0.49922752 0.8096724 ]
   [0.7215921  0.8590143  0.47600284]
   [0.7092408  0.47192782 0.3793637 ]
   [0.75367206 0.76532215 0.33729264]
   [0.7304386  0.54024035 0.13130514]
   [0.8224923  0.7232164  0.10264108]
   [0.82917285 0.55796033 0.0605888 ]
   [0.74327725 0.8408019  0.03150535]
   [0.7133452  0.49034306 0.1213013 ]
   [0.7593758  0.750098   0.0091461 ]
   [0.7421198  0.60297775 0.02738098]]]]
[[[[0.45421624 0.6085266  0.6123725 ]
   [0.41651857 0.6473799  0.44100156]
   [0.42133388 0.5784988  0.71641785]
   [0.42177486 0.7006408  0.6757935 ]
   [0.43062294 0.55285764 0.7585976 ]
   [0.50552845 0.7934765  0.8118563 ]
   [0.52666587 0.50061035 0.772964  ]
   [0.7202746  0.866115   0.45572057]
   [0.7050423  0.47634327 0.3779474 ]
   [0.748

[[[[0.4450388  0.6123184  0.43805623]
   [0.41312775 0.6431502  0.5714038 ]
   [0.41122776 0.59712964 0.67421097]
   [0.41897744 0.706298   0.5355766 ]
   [0.4106896  0.59963506 0.59009886]
   [0.53160876 0.78727925 0.73047453]
   [0.5237627  0.52910066 0.8205636 ]
   [0.7285225  0.8454799  0.4248119 ]
   [0.6990731  0.46866608 0.48967418]
   [0.74940413 0.74810356 0.3064092 ]
   [0.72851384 0.5510291  0.14354452]
   [0.84119457 0.71899915 0.07124487]
   [0.8379444  0.5680773  0.05076861]
   [0.73942703 0.7354471  0.01772533]
   [0.7091338  0.48405218 0.18805002]
   [0.7457091  0.5941229  0.03334656]
   [0.7401291  0.59909344 0.05247486]]]]
[[[[0.4452889  0.6137258  0.48386905]
   [0.41481766 0.6452539  0.47782576]
   [0.41288805 0.5978287  0.5880775 ]
   [0.42051575 0.7065975  0.5611652 ]
   [0.4131593  0.5980599  0.6403408 ]
   [0.5332403  0.7870822  0.7344667 ]
   [0.52282447 0.53138965 0.8250642 ]
   [0.7277054  0.8404851  0.4161667 ]
   [0.6969973  0.46494865 0.4408867 ]
   [0.747

[[[[0.4488103  0.6000965  0.53207165]
   [0.41768187 0.62885565 0.33185518]
   [0.4187207  0.5826461  0.4075308 ]
   [0.42321563 0.6878852  0.6860147 ]
   [0.42496824 0.5819213  0.65510744]
   [0.5328388  0.77090454 0.78199714]
   [0.5268443  0.5151274  0.83116674]
   [0.73380893 0.8325884  0.50975657]
   [0.718949   0.44021118 0.52308214]
   [0.75668275 0.74970496 0.37728444]
   [0.71209013 0.51700014 0.3278937 ]
   [0.85480464 0.7012199  0.04123459]
   [0.8420374  0.55716527 0.03586344]
   [0.7520629  0.7230532  0.01101644]
   [0.71635973 0.47689754 0.21007362]
   [0.7390468  0.57227474 0.04045556]
   [0.73319334 0.58855593 0.08957247]]]]
[[[[0.45014796 0.59877515 0.5225832 ]
   [0.41944298 0.62646675 0.3184503 ]
   [0.42090994 0.58109844 0.39683077]
   [0.42306587 0.685783   0.6186547 ]
   [0.42619953 0.57889277 0.6628891 ]
   [0.53235966 0.77368873 0.8154798 ]
   [0.52647936 0.5137758  0.84930104]
   [0.73177457 0.82649195 0.48281097]
   [0.7148549  0.445202   0.5085356 ]
   [0.757

[[[[0.4583231  0.60070443 0.3102563 ]
   [0.42602998 0.63284165 0.4499808 ]
   [0.4294916  0.5826703  0.55699915]
   [0.42720383 0.6934869  0.7416825 ]
   [0.42838487 0.5801708  0.6747008 ]
   [0.53062105 0.7849924  0.8634518 ]
   [0.5221325  0.5179516  0.75244445]
   [0.73561406 0.8352109  0.54630584]
   [0.7183759  0.44601434 0.4485359 ]
   [0.75612795 0.7518091  0.33548716]
   [0.7128979  0.52025986 0.33539054]
   [0.8380736  0.7086915  0.06733359]
   [0.82798636 0.5624636  0.05323872]
   [0.7383443  0.77345294 0.02508081]
   [0.7153634  0.4807241  0.26551887]
   [0.7365705  0.57087386 0.04648833]
   [0.7293447  0.5962541  0.08425618]]]]
[[[[0.45773882 0.6043847  0.3647574 ]
   [0.4256317  0.63617086 0.40618312]
   [0.42917138 0.5850749  0.62911314]
   [0.427973   0.6948918  0.73680365]
   [0.4306986  0.5789237  0.6993806 ]
   [0.52993435 0.7831797  0.87019193]
   [0.5223391  0.5186193  0.75512886]
   [0.7346318  0.8386673  0.4931043 ]
   [0.71704143 0.44946405 0.5110613 ]
   [0.753

[[[[0.45267278 0.60382015 0.4660182 ]
   [0.4217245  0.63311315 0.34626296]
   [0.42661345 0.5847783  0.6573067 ]
   [0.4266157  0.69292533 0.7340665 ]
   [0.4318132  0.5827378  0.6755488 ]
   [0.533768   0.7879733  0.86163497]
   [0.5255157  0.5175365  0.8167947 ]
   [0.7336798  0.8422358  0.4826267 ]
   [0.7171849  0.44896576 0.4983341 ]
   [0.7543618  0.7590883  0.26782867]
   [0.7158305  0.52580655 0.1817397 ]
   [0.8459023  0.7139797  0.03577024]
   [0.8380933  0.55958736 0.03559162]
   [0.7381369  0.7779615  0.02199751]
   [0.7179646  0.48405096 0.2169564 ]
   [0.7412855  0.595548   0.02316354]
   [0.73354906 0.60081726 0.05212209]]]]
[[[[0.45340532 0.6079764  0.5043135 ]
   [0.42236423 0.63589495 0.45945776]
   [0.42589188 0.58693886 0.6462033 ]
   [0.4262006  0.6937694  0.75297135]
   [0.42904624 0.57877487 0.72122926]
   [0.53020835 0.7863614  0.8608246 ]
   [0.5240958  0.5148885  0.8291645 ]
   [0.73178357 0.83211344 0.5627128 ]
   [0.71568125 0.4506919  0.52544516]
   [0.754

[[[[0.45866856 0.66409403 0.43071198]
   [0.42411566 0.69381636 0.49725142]
   [0.42710668 0.64381087 0.32052383]
   [0.41855893 0.7519988  0.5919088 ]
   [0.42009053 0.633259   0.58936644]
   [0.5276346  0.845976   0.89326715]
   [0.52349234 0.57735795 0.8328512 ]
   [0.7291359  0.9163429  0.46943438]
   [0.70544755 0.50939643 0.43204522]
   [0.7586814  0.808838   0.4832176 ]
   [0.71939325 0.56434554 0.22000939]
   [0.85781515 0.77145386 0.05562954]
   [0.84175396 0.609617   0.04900568]
   [0.74812716 0.8882512  0.02950596]
   [0.7162286  0.531096   0.14749214]
   [0.74513125 0.6320133  0.0238967 ]
   [0.740149   0.62013435 0.05773841]]]]
[[[[0.45943135 0.66955394 0.5366581 ]
   [0.4248019  0.7010765  0.48706308]
   [0.42657572 0.6479354  0.5233464 ]
   [0.42081738 0.75556916 0.7206312 ]
   [0.4200676  0.6351315  0.61859745]
   [0.5279914  0.84957737 0.8717781 ]
   [0.5264206  0.5760964  0.8293224 ]
   [0.7296853  0.9225477  0.46175107]
   [0.7127432  0.5210613  0.50058514]
   [0.760

[[[[0.44727945 0.66079617 0.5641613 ]
   [0.41614097 0.6924791  0.50241095]
   [0.41650078 0.64364827 0.6094701 ]
   [0.41938934 0.7573869  0.73996806]
   [0.41837567 0.64539057 0.5425912 ]
   [0.53167725 0.857274   0.8496187 ]
   [0.52813435 0.5810513  0.7868966 ]
   [0.73767513 0.9248883  0.40722477]
   [0.712482   0.5252616  0.4441938 ]
   [0.7575178  0.8182787  0.46369255]
   [0.72285455 0.60065234 0.20583111]
   [0.8711262  0.78503627 0.03206781]
   [0.83826065 0.6091156  0.03819512]
   [0.7592399  0.91463345 0.03177613]
   [0.71604514 0.5446199  0.22368999]
   [0.7442446  0.6449263  0.01329316]
   [0.73607415 0.6361522  0.04038454]]]]
[[[[0.45060724 0.6566026  0.5355055 ]
   [0.41887674 0.68764865 0.34327418]
   [0.41894004 0.64174277 0.5498173 ]
   [0.420899   0.75734085 0.7581291 ]
   [0.42055184 0.648268   0.51840866]
   [0.5325074  0.8587002  0.86157787]
   [0.527956   0.5812311  0.786756  ]
   [0.7367963  0.92633545 0.41877985]
   [0.7118186  0.52506155 0.46078953]
   [0.757

[[[[0.70242155 0.5130022  0.25218678]
   [0.6945464  0.51765513 0.31036603]
   [0.71311605 0.48687834 0.2758215 ]
   [0.7126653  0.5501787  0.24405766]
   [0.76480305 0.41593844 0.19740078]
   [0.7275536  0.6920044  0.2042076 ]
   [0.7709777  0.3293722  0.2443738 ]
   [0.5936693  0.7417078  0.05200214]
   [0.75261605 0.32426324 0.12467755]
   [0.58976066 0.7509121  0.09332749]
   [0.75874245 0.32949615 0.11666101]
   [0.58587533 0.6587442  0.03517945]
   [0.5893806  0.48864517 0.05614015]
   [0.6664474  0.6907886  0.06139232]
   [0.72378373 0.5096233  0.11098162]
   [0.5902897  0.75741714 0.08337858]
   [0.72701836 0.42948174 0.05959891]]]]
[[[[0.70110345 0.5794416  0.179486  ]
   [0.6792022  0.59375733 0.17308177]
   [0.70709556 0.5519614  0.25453848]
   [0.70785    0.6386469  0.23202282]
   [0.7597005  0.49519905 0.19902892]
   [0.74483955 0.80870044 0.25405988]
   [0.7850841  0.39256364 0.23090562]
   [0.58582944 0.84383816 0.08959546]
   [0.75300264 0.3776154  0.10410327]
   [0.587

[[[[0.2927338  0.2959758  0.38692153]
   [0.24387854 0.32920074 0.29215404]
   [0.25612658 0.26334822 0.30438146]
   [0.2598066  0.37796628 0.5775069 ]
   [0.27433825 0.19827078 0.35397246]
   [0.45481545 0.51030266 0.8140972 ]
   [0.4796589  0.01669054 0.27910027]
   [0.7264578  0.5960739  0.3749184 ]
   [0.7075536  0.00995427 0.05608319]
   [0.74372476 0.59897876 0.08451111]
   [0.74932325 0.21701574 0.06086028]
   [0.7995597  0.5417801  0.02433373]
   [0.8190527  0.01226456 0.02382218]
   [0.76334715 0.6175542  0.05720961]
   [0.74405396 0.30814326 0.00592991]
   [0.76087415 0.61688876 0.01415444]
   [0.7702075  0.5323402  0.00347234]]]]
[[[[0.2828058  0.3425858  0.37003237]
   [0.24237476 0.3772874  0.47447652]
   [0.2553263  0.30850875 0.38159874]
   [0.2743862  0.42452538 0.56600773]
   [0.2869132  0.24512522 0.37090516]
   [0.48755452 0.5605209  0.862976  ]
   [0.49579966 0.08305934 0.82637256]
   [0.75845975 0.6369057  0.08183334]
   [0.6779709  0.01238545 0.06719842]
   [0.461

[[[[0.42698604 0.19966659 0.59241146]
   [0.39543235 0.22627512 0.5911917 ]
   [0.3965854  0.19530022 0.6115221 ]
   [0.40859675 0.33807153 0.6754308 ]
   [0.40586147 0.25818855 0.49909097]
   [0.5411992  0.46411428 0.70882523]
   [0.5842054  0.24281786 0.77921635]
   [0.76766205 0.47649497 0.3409081 ]
   [0.7263675  0.16459453 0.66755193]
   [0.72559804 0.719988   0.11242083]
   [0.7377759  0.04127332 0.3493908 ]
   [0.81504714 0.4964891  0.04864435]
   [0.7920031  0.53640074 0.0617867 ]
   [0.7493405  0.24201956 0.07631471]
   [0.7487581  0.09811407 0.05923431]
   [0.71347994 0.75241363 0.08039828]
   [0.7664558  0.02194074 0.04261034]]]]
[[[[0.42413962 0.24834315 0.5546129 ]
   [0.38275766 0.2741034  0.6335353 ]
   [0.39109403 0.23410729 0.5713804 ]
   [0.4003911  0.38301438 0.7043612 ]
   [0.40131795 0.2742812  0.4500894 ]
   [0.528108   0.5024426  0.48763314]
   [0.5745907  0.27755934 0.67615384]
   [0.7578641  0.48922512 0.18063687]
   [0.72230667 0.19756314 0.6598669 ]
   [0.757

[[[[0.41796955 0.35657716 0.40404025]
   [0.38094005 0.37887156 0.534417  ]
   [0.38322172 0.3603261  0.6440669 ]
   [0.38409454 0.47830588 0.642949  ]
   [0.3838405  0.42639792 0.57790047]
   [0.51788116 0.6142367  0.74209845]
   [0.55032635 0.4000742  0.8489595 ]
   [0.7647426  0.5342555  0.5072343 ]
   [0.7142758  0.31391597 0.71201295]
   [0.760358   0.34456456 0.02889201]
   [0.7353412  0.21883534 0.2974992 ]
   [0.7987907  0.7067604  0.10863701]
   [0.79642576 0.7009758  0.07841421]
   [0.75003636 0.33890444 0.0621998 ]
   [0.73856425 0.23365971 0.07087523]
   [0.76105803 0.03939468 0.00993643]
   [0.67148125 0.03132379 0.04523741]]]]
[[[[0.41496453 0.34874198 0.49793085]
   [0.37969002 0.3746661  0.48915455]
   [0.37966824 0.35070848 0.59084064]
   [0.38614306 0.4801111  0.6500587 ]
   [0.38577688 0.42365536 0.53000355]
   [0.5140813  0.6031596  0.6579031 ]
   [0.5425164  0.39115235 0.725586  ]
   [0.760483   0.5440043  0.43327078]
   [0.70414543 0.30898133 0.6219344 ]
   [0.775

[[[[0.4017465  0.37051362 0.5788472 ]
   [0.364356   0.40075713 0.7281043 ]
   [0.36962527 0.36172622 0.83375984]
   [0.38160932 0.4985206  0.62555844]
   [0.38007295 0.4022828  0.5103737 ]
   [0.52597207 0.6021079  0.73820007]
   [0.5504701  0.3871101  0.87283605]
   [0.772161   0.52691597 0.27530867]
   [0.70859283 0.29672176 0.6804386 ]
   [0.757643   0.32004437 0.04636664]
   [0.7425009  0.210359   0.31217188]
   [0.84450483 0.5978791  0.03287479]
   [0.84274805 0.42377    0.04247633]
   [0.73436564 0.3322903  0.06051216]
   [0.7287941  0.24627337 0.06410382]
   [0.72792256 0.03278682 0.01959337]
   [0.7319712  0.0354686  0.05912551]]]]
[[[[0.40317282 0.37304598 0.51047015]
   [0.36562777 0.40229982 0.75540745]
   [0.37158954 0.36298868 0.824525  ]
   [0.3825605  0.49781907 0.6223763 ]
   [0.3813821  0.4006816  0.4966029 ]
   [0.52499396 0.5995821  0.66323715]
   [0.5460106  0.3889959  0.68919927]
   [0.77146184 0.52535915 0.39947325]
   [0.70967555 0.30126607 0.67187536]
   [0.768

[[[[0.44638205 0.27115667 0.40530768]
   [0.41532218 0.30176207 0.6142946 ]
   [0.4113027  0.27690643 0.6545111 ]
   [0.40848887 0.4138353  0.5679403 ]
   [0.40611777 0.3602581  0.36152825]
   [0.5293028  0.54372966 0.835585  ]
   [0.53536224 0.3456208  0.74009776]
   [0.77562416 0.5310654  0.2288466 ]
   [0.7245564  0.2839854  0.5004155 ]
   [0.76527566 0.3232316  0.04364387]
   [0.74406075 0.1987562  0.14461668]
   [0.83557695 0.5482109  0.02697739]
   [0.8213763  0.39703763 0.06368922]
   [0.7470061  0.2798395  0.07537131]
   [0.7331564  0.16580312 0.1269246 ]
   [0.7564489  0.03404942 0.01503086]
   [0.76109195 0.04118448 0.02807927]]]]
[[[[0.4453939  0.26990664 0.44052953]
   [0.41215143 0.29933032 0.63033754]
   [0.40939075 0.27649772 0.71458673]
   [0.40661392 0.41245925 0.5548615 ]
   [0.405503   0.36308035 0.41605794]
   [0.5298189  0.55039746 0.8508416 ]
   [0.5337465  0.3469251  0.5780812 ]
   [0.7799125  0.53629446 0.26237217]
   [0.7285751  0.2890751  0.5681261 ]
   [0.763

[[[[0.4443702  0.46959287 0.6284116 ]
   [0.4046104  0.49522954 0.5818686 ]
   [0.4099536  0.46655032 0.6717656 ]
   [0.3941319  0.59776086 0.58841527]
   [0.40326935 0.53088355 0.3871285 ]
   [0.5213818  0.71833646 0.6991992 ]
   [0.5421862  0.55544794 0.5894422 ]
   [0.765248   0.6914271  0.40211138]
   [0.7096518  0.47328144 0.44994187]
   [0.7566578  0.48900574 0.07391972]
   [0.72711146 0.3738352  0.1796845 ]
   [0.7960848  0.84696865 0.1095061 ]
   [0.81498027 0.6422096  0.07066179]
   [0.7365004  0.46388492 0.09755125]
   [0.71190035 0.34051448 0.09136587]
   [0.7649038  0.26249546 0.02713352]
   [0.760273   0.25297353 0.02179177]]]]
[[[[0.43001533 0.499276   0.5590701 ]
   [0.39404377 0.5207497  0.43721056]
   [0.3969795  0.4999033  0.61512065]
   [0.38584614 0.6169107  0.66401964]
   [0.3950343  0.5659456  0.35115385]
   [0.5203124  0.7459105  0.63569444]
   [0.5466659  0.5681958  0.71648216]
   [0.7700341  0.6973127  0.44519982]
   [0.7184218  0.4988975  0.43589416]
   [0.747

[[[[0.4317485  0.5234739  0.5329828 ]
   [0.400568   0.5436523  0.524075  ]
   [0.40249813 0.5319549  0.70026004]
   [0.40440077 0.6381396  0.55870825]
   [0.40552968 0.5916547  0.44256803]
   [0.5333898  0.7598845  0.56150305]
   [0.53794074 0.5857394  0.6305859 ]
   [0.76881015 0.7208066  0.44444183]
   [0.6879053  0.5366224  0.555283  ]
   [0.7519004  0.5417603  0.18137778]
   [0.7260176  0.42956123 0.35278505]
   [0.8167608  0.82975256 0.08074941]
   [0.836612   0.648296   0.05715667]
   [0.746421   0.55036974 0.05507686]
   [0.7504741  0.45480788 0.04434539]
   [0.7763759  0.47134495 0.01488128]
   [0.7621783  0.40978956 0.02940009]]]]
[[[[0.43490764 0.5237989  0.3507319 ]
   [0.40157247 0.5454585  0.58604133]
   [0.40459523 0.52979803 0.74844784]
   [0.401991   0.6415702  0.5000372 ]
   [0.40504658 0.5906434  0.437539  ]
   [0.54070014 0.7568222  0.69608104]
   [0.5387578  0.58026046 0.57969123]
   [0.7702904  0.6978647  0.52091867]
   [0.69041514 0.53256476 0.650352  ]
   [0.758

[[[[0.4305521  0.51647323 0.58395624]
   [0.40167066 0.53973365 0.53435504]
   [0.40354395 0.5199075  0.6484924 ]
   [0.4061422  0.6265926  0.69267446]
   [0.41006267 0.5695208  0.52758926]
   [0.5342021  0.72742164 0.6452507 ]
   [0.55360526 0.56564766 0.74304485]
   [0.76004505 0.68790495 0.53656435]
   [0.6896454  0.5020482  0.6488391 ]
   [0.7472524  0.4723326  0.18304133]
   [0.7259054  0.40597543 0.2790245 ]
   [0.8215612  0.79346347 0.10290255]
   [0.838645   0.6416355  0.07060394]
   [0.7454394  0.5358318  0.06050022]
   [0.7494104  0.38180146 0.14937885]
   [0.7633664  0.45005113 0.02528597]
   [0.75829166 0.39243776 0.01712769]]]]
[[[[0.43480384 0.518609   0.44520226]
   [0.40518546 0.54340875 0.49286655]
   [0.40603548 0.5222018  0.6105431 ]
   [0.4075848  0.626037   0.69822913]
   [0.41123843 0.5689292  0.522886  ]
   [0.5352463  0.7274531  0.64907616]
   [0.55317235 0.5667363  0.7466071 ]
   [0.7610141  0.695904   0.48723996]
   [0.6901433  0.50493866 0.63222855]
   [0.748

[[[[0.42537123 0.51950777 0.57220286]
   [0.39555705 0.5471381  0.5738714 ]
   [0.3964144  0.5193471  0.6328493 ]
   [0.4001771  0.63218486 0.7121172 ]
   [0.40560874 0.5649972  0.4129915 ]
   [0.5344647  0.72580934 0.6834675 ]
   [0.55021536 0.56131065 0.73111546]
   [0.7634692  0.68812484 0.52014744]
   [0.69217014 0.4864385  0.6118454 ]
   [0.74068594 0.48415178 0.20651905]
   [0.7259461  0.39874858 0.24714041]
   [0.8355248  0.7523553  0.08991499]
   [0.8445818  0.61436605 0.04223678]
   [0.73831356 0.5133966  0.05377141]
   [0.7441653  0.40558922 0.05773938]
   [0.7605998  0.4330717  0.02811679]
   [0.75391984 0.43049988 0.01941978]]]]
[[[[0.42229566 0.5153775  0.6197766 ]
   [0.39017743 0.539148   0.43805853]
   [0.39204657 0.5175999  0.571019  ]
   [0.39858517 0.6288305  0.6706354 ]
   [0.40218192 0.5695345  0.46510404]
   [0.52415085 0.7301905  0.75098264]
   [0.55038667 0.56069946 0.74046487]
   [0.7581307  0.6945826  0.63027424]
   [0.6929385  0.4871872  0.604302  ]
   [0.747

[[[[0.4203006  0.51361585 0.57746875]
   [0.38765654 0.53957546 0.597294  ]
   [0.3891991  0.51556873 0.5555414 ]
   [0.3980964  0.62822336 0.6908365 ]
   [0.39845568 0.56722003 0.4337362 ]
   [0.5252139  0.7258611  0.7282342 ]
   [0.546794   0.5608743  0.7507542 ]
   [0.76350486 0.6866584  0.60016966]
   [0.6958859  0.48646373 0.5661429 ]
   [0.74811053 0.4530135  0.25488222]
   [0.7297393  0.39733943 0.26092455]
   [0.81858635 0.75246346 0.11260249]
   [0.83575666 0.60140514 0.06489433]
   [0.74127305 0.51888347 0.08457239]
   [0.7515937  0.3943375  0.07144365]
   [0.7607581  0.43192634 0.03371938]
   [0.7521845  0.2892666  0.01682917]]]]
[[[[0.4209801  0.51718223 0.55464697]
   [0.38835883 0.54388803 0.6680237 ]
   [0.39008182 0.5163387  0.5991421 ]
   [0.39826363 0.6326186  0.7032819 ]
   [0.40049037 0.5641565  0.40471527]
   [0.5263325  0.7278054  0.7433127 ]
   [0.54891914 0.5588531  0.7288064 ]
   [0.76234543 0.6880399  0.61654437]
   [0.69718474 0.48475742 0.5803222 ]
   [0.747

[[[[0.32952955 0.5124626  0.5410019 ]
   [0.2976013  0.5387863  0.53094137]
   [0.29911777 0.51569676 0.78087825]
   [0.30262464 0.62734807 0.7229583 ]
   [0.3033433  0.5746537  0.59228534]
   [0.4373415  0.7214236  0.6859515 ]
   [0.45625705 0.54936314 0.62877566]
   [0.71364737 0.67244285 0.61350024]
   [0.60322064 0.48241717 0.35316622]
   [0.66788507 0.40977317 0.57293093]
   [0.6427596  0.38469335 0.27049085]
   [0.7893254  0.7101211  0.07272309]
   [0.7979547  0.5827891  0.05722028]
   [0.72486115 0.6169602  0.07967766]
   [0.6783902  0.22775105 0.13238722]
   [0.6921761  0.37728858 0.04627158]
   [0.66991913 0.25563312 0.04678576]]]]
[[[[0.31631672 0.5177401  0.6039113 ]
   [0.2835713  0.54222286 0.64164853]
   [0.28807494 0.518029   0.6992059 ]
   [0.29359186 0.6311207  0.6542267 ]
   [0.2934392  0.57562494 0.48436567]
   [0.42377675 0.7152264  0.8555003 ]
   [0.4548881  0.5522568  0.741688  ]
   [0.70461005 0.67002416 0.5339343 ]
   [0.60604435 0.47287798 0.3075001 ]
   [0.657

[[[[0.27957207 0.5201741  0.5816945 ]
   [0.25482625 0.53214157 0.56043184]
   [0.25590795 0.5270815  0.5093563 ]
   [0.2620876  0.60615844 0.65582174]
   [0.2639182  0.5959543  0.6339923 ]
   [0.37956727 0.71830934 0.82124907]
   [0.40383524 0.5530423  0.8461189 ]
   [0.6421546  0.6921432  0.62958556]
   [0.5502913  0.47396713 0.35752094]
   [0.6131822  0.418966   0.39219922]
   [0.60184157 0.399967   0.4073912 ]
   [0.7418348  0.74059814 0.2283141 ]
   [0.7105299  0.6149336  0.25352985]
   [0.609629   0.43488428 0.16132301]
   [0.5786023  0.34860286 0.44259405]
   [0.6259432  0.41508782 0.09752724]
   [0.6348196  0.4020291  0.05779585]]]]
[[[[0.27852562 0.5196512  0.5564493 ]
   [0.25519928 0.5316453  0.55813044]
   [0.25602955 0.52662736 0.5144224 ]
   [0.2626769  0.6069939  0.66606444]
   [0.2643706  0.596846   0.5960845 ]
   [0.38071817 0.71584916 0.7951744 ]
   [0.4064291  0.55445385 0.8388873 ]
   [0.64274716 0.67955446 0.6354542 ]
   [0.5456456  0.47510204 0.37655455]
   [0.614

[[[[0.31153083 0.52537143 0.34891647]
   [0.28690886 0.5393034  0.47231832]
   [0.28810948 0.52942646 0.6004744 ]
   [0.2905306  0.6200177  0.47291285]
   [0.28738496 0.59294486 0.47313553]
   [0.4039349  0.7175847  0.7709919 ]
   [0.4255072  0.5563992  0.8018235 ]
   [0.6789715  0.6719429  0.5799331 ]
   [0.5637075  0.4807186  0.5174051 ]
   [0.64150506 0.43547794 0.4826328 ]
   [0.61068356 0.3971783  0.4157407 ]
   [0.7371968  0.71360695 0.23669791]
   [0.72499156 0.56958294 0.1274856 ]
   [0.69942343 0.6358966  0.26224884]
   [0.6268514  0.31311697 0.29495972]
   [0.6906044  0.418158   0.08857264]
   [0.65784836 0.39591286 0.05604759]]]]
[[[[0.32298353 0.52058196 0.3558398 ]
   [0.29056716 0.535388   0.5656634 ]
   [0.28960645 0.5276898  0.5806123 ]
   [0.29383883 0.61541563 0.4382148 ]
   [0.2947503  0.59406024 0.44796067]
   [0.4074508  0.71411264 0.7918316 ]
   [0.4278797  0.5543964  0.6744893 ]
   [0.6691226  0.6746408  0.4824546 ]
   [0.5621256  0.48034614 0.5153525 ]
   [0.640

[[[[0.3093121  0.47083732 0.60217595]
   [0.28186327 0.48725602 0.6400634 ]
   [0.28066704 0.4837029  0.61784   ]
   [0.27845976 0.5706569  0.5724136 ]
   [0.27962124 0.562266   0.51926094]
   [0.39084932 0.7119285  0.7188885 ]
   [0.41069192 0.5544073  0.6475501 ]
   [0.6647168  0.68077743 0.6439805 ]
   [0.5427631  0.4869507  0.4620815 ]
   [0.6406089  0.42030722 0.42803732]
   [0.59502256 0.39654884 0.28503668]
   [0.77215403 0.75988793 0.23374325]
   [0.77295697 0.62267506 0.11247381]
   [0.74421537 0.579677   0.0667041 ]
   [0.6118504  0.3123012  0.22165106]
   [0.67823994 0.400464   0.02774127]
   [0.64361    0.25506076 0.0386996 ]]]]
[[[[0.30212367 0.46845013 0.5139587 ]
   [0.27107435 0.48455048 0.5491653 ]
   [0.27111623 0.48078272 0.53702277]
   [0.27455273 0.5639731  0.52379054]
   [0.2766466  0.55536425 0.58524203]
   [0.38435513 0.7077482  0.58724964]
   [0.41426882 0.5546873  0.8065025 ]
   [0.65886885 0.6791675  0.6454576 ]
   [0.553568   0.4733013  0.38432348]
   [0.637

[[[[0.20632254 0.5318474  0.05487921]
   [0.16862464 0.529515   0.07199892]
   [0.17123732 0.52823263 0.06251621]
   [0.18630496 0.62540483 0.16642883]
   [0.19048421 0.5783559  0.13180475]
   [0.28069523 0.7218747  0.6614994 ]
   [0.29855695 0.5464371  0.78802717]
   [0.5575237  0.66216385 0.6512484 ]
   [0.45651075 0.46531057 0.482062  ]
   [0.53292763 0.41126823 0.48009643]
   [0.50192714 0.3839857  0.4107423 ]
   [0.6219739  0.68437195 0.30863976]
   [0.592486   0.5471425  0.38169104]
   [0.7071504  0.47510013 0.08395619]
   [0.50457925 0.27660653 0.401198  ]
   [0.72674155 0.56345534 0.07690826]
   [0.6871016  0.41981134 0.0409101 ]]]]
[[[[0.21146236 0.5333624  0.10201071]
   [0.17545512 0.5308999  0.08868285]
   [0.18736348 0.5362526  0.04995248]
   [0.18876438 0.6263428  0.17788558]
   [0.19943568 0.57517546 0.14678022]
   [0.28112203 0.7265127  0.64152724]
   [0.29682755 0.5452131  0.7176024 ]
   [0.5599543  0.6533718  0.64680743]
   [0.45266497 0.46303177 0.43143675]
   [0.530

[[[[0.31425324 0.34728885 0.4124315 ]
   [0.2799571  0.34384346 0.51417047]
   [0.2833973  0.34281057 0.55143404]
   [0.23442122 0.4162354  0.45949477]
   [0.24515831 0.4041414  0.493599  ]
   [0.2675883  0.5925782  0.6754507 ]
   [0.32784006 0.47171032 0.29731515]
   [0.556584   0.65397555 0.66837287]
   [0.50563234 0.4783256  0.243713  ]
   [0.5036386  0.408519   0.47107562]
   [0.48209745 0.3839173  0.3164759 ]
   [0.6267556  0.7283453  0.26786846]
   [0.6042197  0.58655405 0.36157832]
   [0.4928727  0.3550249  0.07378667]
   [0.4837103  0.29825342 0.23496531]
   [0.49608573 0.3849815  0.05136351]
   [0.50000864 0.378762   0.04723162]]]]
[[[[0.31576657 0.3461399  0.4311431 ]
   [0.27942502 0.34162483 0.523654  ]
   [0.28354594 0.34123325 0.56568366]
   [0.23148954 0.41424474 0.45290378]
   [0.24759322 0.39463112 0.35153753]
   [0.2652257  0.58993936 0.6313074 ]
   [0.33550185 0.47139812 0.38390195]
   [0.55842555 0.6653936  0.4999922 ]
   [0.5140662  0.48490322 0.22583063]
   [0.506

[[[[0.19802555 0.48855817 0.06977155]
   [0.17409365 0.49200296 0.08821595]
   [0.17675716 0.49219877 0.06941027]
   [0.19060314 0.6265403  0.16693184]
   [0.19291678 0.5975828  0.13413578]
   [0.2903868  0.7256018  0.80202395]
   [0.30143765 0.5652528  0.70427823]
   [0.5660068  0.66741335 0.49673367]
   [0.43788505 0.47467968 0.50419074]
   [0.5291474  0.414136   0.49755755]
   [0.48637438 0.3970033  0.26615196]
   [0.68970895 0.6887437  0.26311874]
   [0.6352805  0.5409717  0.32385   ]
   [0.73009396 0.4124577  0.08431146]
   [0.5013407  0.30064785 0.32554892]
   [0.7276145  0.5503077  0.08863078]
   [0.7254231  0.41351694 0.03284892]]]]
[[[[0.21563366 0.49841842 0.07168951]
   [0.19092321 0.54325247 0.05978092]
   [0.18576473 0.51482177 0.05082134]
   [0.19393158 0.6468757  0.19334403]
   [0.20482957 0.5883472  0.13469733]
   [0.28131303 0.7295753  0.6201249 ]
   [0.29934716 0.5668884  0.6705036 ]
   [0.5664103  0.6748771  0.678397  ]
   [0.4509765  0.46712005 0.4159111 ]
   [0.529

[[[[0.23651981 0.53324616 0.06982831]
   [0.1967387  0.5620588  0.07824232]
   [0.1985654  0.55968297 0.07414348]
   [0.199366   0.66497123 0.14689523]
   [0.20550142 0.5912613  0.10977968]
   [0.2654084  0.7191708  0.73236275]
   [0.28590354 0.5531899  0.5405931 ]
   [0.5699085  0.6598832  0.61642796]
   [0.44099462 0.4594991  0.4556329 ]
   [0.52377737 0.4349737  0.4374441 ]
   [0.5058507  0.38851333 0.25287467]
   [0.67244506 0.6911785  0.34898454]
   [0.6039968  0.52431476 0.45862964]
   [0.7175087  0.47885177 0.13460289]
   [0.54758304 0.26572308 0.14937866]
   [0.7494084  0.5363352  0.08781445]
   [0.7140596  0.37812507 0.03646068]]]]
[[[[0.2512259  0.53925675 0.09519624]
   [0.20852344 0.56086576 0.0565291 ]
   [0.1969959  0.5597849  0.06430554]
   [0.20178983 0.667187   0.18147883]
   [0.20585029 0.5895681  0.11461336]
   [0.26669043 0.71630025 0.6316912 ]
   [0.28539306 0.55701625 0.67049265]
   [0.5596482  0.6613319  0.68094003]
   [0.44026074 0.46154985 0.47236267]
   [0.512

[[[[0.26679838 0.5402709  0.1682872 ]
   [0.23863988 0.5615585  0.07854176]
   [0.2528182  0.54338735 0.09633673]
   [0.22449243 0.6574471  0.15762989]
   [0.22939079 0.5865438  0.13125288]
   [0.28024676 0.73124444 0.5847742 ]
   [0.29879996 0.5447903  0.51709574]
   [0.55356544 0.66321295 0.5933551 ]
   [0.4401965  0.4480405  0.44979185]
   [0.52830386 0.4160915  0.5130567 ]
   [0.5009043  0.38795197 0.22084184]
   [0.5866669  0.65431607 0.36447856]
   [0.5412773  0.50906587 0.40501803]
   [0.69482964 0.5228934  0.18473797]
   [0.5011581  0.289334   0.2560528 ]
   [0.71287966 0.52306485 0.21122862]
   [0.6949984  0.5170338  0.20475395]]]]
[[[[0.2703599  0.5384896  0.19269364]
   [0.2554322  0.5488864  0.14797752]
   [0.25635543 0.54075444 0.1463696 ]
   [0.22572494 0.65571105 0.17614985]
   [0.23131406 0.58463526 0.16142382]
   [0.2771195  0.7309352  0.49765328]
   [0.3019516  0.5406461  0.57911956]
   [0.55315685 0.6751773  0.5649747 ]
   [0.44640312 0.44274223 0.39106935]
   [0.528

[[[[0.22822826 0.56041205 0.13850887]
   [0.20202927 0.582249   0.07129049]
   [0.20496419 0.56595695 0.08720221]
   [0.20815322 0.6726262  0.17829722]
   [0.214343   0.58920896 0.13384815]
   [0.27583706 0.73169017 0.49811804]
   [0.30246925 0.5474654  0.7847543 ]
   [0.5493202  0.6582264  0.67621356]
   [0.4353329  0.46231997 0.4447125 ]
   [0.50423324 0.4283989  0.46558574]
   [0.49317893 0.39609763 0.38740122]
   [0.5602766  0.67158    0.32562032]
   [0.53547573 0.5457579  0.28244817]
   [0.6524483  0.55911815 0.21764712]
   [0.471094   0.31950158 0.45016074]
   [0.6820285  0.54102725 0.29329917]
   [0.6762192  0.5389445  0.2484732 ]]]]
[[[[0.24273852 0.5452397  0.09596458]
   [0.20376043 0.5642662  0.08567063]
   [0.21641585 0.5595673  0.08731061]
   [0.2089055  0.6533313  0.14255531]
   [0.21442752 0.5883019  0.13337427]
   [0.27652386 0.7316457  0.48355904]
   [0.2991503  0.5485126  0.79010415]
   [0.55073315 0.65785015 0.66424704]
   [0.4316299  0.4615206  0.4245001 ]
   [0.510

[[[[0.22213036 0.5626953  0.09817816]
   [0.18887839 0.5733504  0.0725841 ]
   [0.19104527 0.55777794 0.0446043 ]
   [0.20452325 0.6758733  0.14391734]
   [0.2098139  0.6084396  0.10927381]
   [0.28090584 0.73256576 0.6222115 ]
   [0.2969132  0.5561734  0.8014051 ]
   [0.5556892  0.6640065  0.62491953]
   [0.44207686 0.4569665  0.5347198 ]
   [0.5128306  0.42080706 0.46210968]
   [0.49122965 0.3931805  0.3710628 ]
   [0.58356255 0.67556185 0.34785178]
   [0.5454595  0.55054206 0.3997436 ]
   [0.5328996  0.41922748 0.22256184]
   [0.49835807 0.3148344  0.24683015]
   [0.6915669  0.48453814 0.19877724]
   [0.6775097  0.49275228 0.15944877]]]]
[[[[0.21714509 0.5600356  0.07505678]
   [0.18431062 0.56995034 0.05871725]
   [0.18577331 0.54051733 0.03697153]
   [0.20140514 0.6710536  0.13970694]
   [0.20700811 0.60483813 0.12039526]
   [0.27739197 0.72970337 0.55028534]
   [0.29665303 0.55487007 0.81731516]
   [0.5569983  0.6656082  0.6120691 ]
   [0.4417541  0.4541163  0.5196958 ]
   [0.512

[[[[0.22319692 0.5586287  0.1170959 ]
   [0.18923824 0.56990916 0.07438192]
   [0.1912784  0.53857297 0.05360016]
   [0.19724718 0.6593985  0.0959325 ]
   [0.20876217 0.5894884  0.11863674]
   [0.2740464  0.731075   0.47331238]
   [0.2902554  0.5532223  0.68076056]
   [0.5536386  0.6609539  0.6528073 ]
   [0.43385488 0.4668883  0.48880866]
   [0.514505   0.42467114 0.49858177]
   [0.48630917 0.39573652 0.38483557]
   [0.5616847  0.67376566 0.35988054]
   [0.51992714 0.5291082  0.40067577]
   [0.531827   0.41945606 0.17623538]
   [0.4702401  0.30850792 0.44559634]
   [0.6925408  0.4355091  0.12164324]
   [0.60086787 0.39917943 0.08236495]]]]
[[[[0.22702436 0.5601443  0.11992464]
   [0.20174526 0.56976223 0.09337976]
   [0.2036699  0.5652385  0.08063725]
   [0.2090504  0.6578902  0.12711962]
   [0.2124004  0.5890562  0.12771896]
   [0.27567148 0.7322742  0.51768076]
   [0.29616356 0.55092764 0.60711527]
   [0.5510989  0.6632781  0.59527755]
   [0.43555832 0.46326417 0.4764092 ]
   [0.528

[[[[0.20246802 0.59817636 0.10177822]
   [0.18768309 0.61397356 0.11164261]
   [0.18911314 0.6062544  0.0669762 ]
   [0.19628042 0.68978065 0.14208375]
   [0.20647985 0.64373684 0.12836158]
   [0.2683638  0.7655008  0.7455639 ]
   [0.2918628  0.59570116 0.7931799 ]
   [0.5447432  0.665629   0.6464114 ]
   [0.41714925 0.5104414  0.58076096]
   [0.52884924 0.41808444 0.35919446]
   [0.4949571  0.3997115  0.4122053 ]
   [0.5795206  0.71478957 0.3688938 ]
   [0.52411926 0.59246755 0.45604527]
   [0.52978486 0.42807543 0.14881524]
   [0.4537819  0.31882805 0.51505435]
   [0.66731    0.5167165  0.18496221]
   [0.52501637 0.40229028 0.24934676]]]]
[[[[0.20944625 0.5972548  0.08991795]
   [0.19248526 0.6150562  0.11120425]
   [0.19434398 0.6056364  0.05978381]
   [0.20062202 0.69194424 0.11330181]
   [0.21083944 0.6456902  0.11852142]
   [0.2737541  0.76715994 0.75362885]
   [0.2967459  0.5871115  0.82443017]
   [0.5454353  0.6641819  0.67348653]
   [0.42934474 0.4981707  0.480652  ]
   [0.531

[[[[0.21559542 0.6388209  0.2781673 ]
   [0.20501493 0.6538784  0.15763123]
   [0.20371902 0.64865255 0.15497668]
   [0.2215364  0.7646196  0.33365938]
   [0.21530068 0.67982364 0.06871544]
   [0.28935018 0.80773777 0.66605014]
   [0.28487614 0.61711866 0.74237806]
   [0.5358869  0.67825234 0.6808309 ]
   [0.40686342 0.5235476  0.6294015 ]
   [0.5344082  0.43692315 0.51671785]
   [0.49859476 0.41448617 0.3593823 ]
   [0.5508719  0.6963236  0.34520113]
   [0.49979913 0.56495464 0.36239502]
   [0.55309236 0.44145942 0.1273659 ]
   [0.47015795 0.3028705  0.5309241 ]
   [0.6662351  0.47950804 0.12486313]
   [0.54597664 0.4222599  0.22644934]]]]
[[[[0.21414617 0.642897   0.24177323]
   [0.20259279 0.65808886 0.14104518]
   [0.20167713 0.6514259  0.13699491]
   [0.22005627 0.7663052  0.3652918 ]
   [0.21313503 0.7173749  0.18033467]
   [0.28898907 0.80949783 0.68064386]
   [0.28753042 0.61488473 0.770617  ]
   [0.53533024 0.68068975 0.68186635]
   [0.40634638 0.52165014 0.61663043]
   [0.533

[[[[0.21386829 0.6425396  0.18767695]
   [0.19459765 0.6580707  0.15110947]
   [0.1969583  0.6525803  0.09052948]
   [0.21270965 0.7527585  0.2469002 ]
   [0.20909992 0.6993947  0.16458441]
   [0.28609192 0.8097829  0.68302554]
   [0.29093635 0.61195457 0.79019386]
   [0.5465234  0.67345655 0.7170285 ]
   [0.41723734 0.5067508  0.4814305 ]
   [0.54305655 0.42089376 0.6886465 ]
   [0.5089507  0.4193576  0.20787817]
   [0.614798   0.68569255 0.3436655 ]
   [0.5421461  0.5482117  0.38866028]
   [0.7451143  0.43720573 0.30642807]
   [0.47136128 0.30215394 0.5441677 ]
   [0.70854676 0.484583   0.16030446]
   [0.68922323 0.5126471  0.1796147 ]]]]
[[[[0.2180526  0.6469841  0.17115109]
   [0.19891642 0.6662012  0.11597032]
   [0.20138596 0.65691453 0.09770029]
   [0.21869086 0.764198   0.3550517 ]
   [0.21393608 0.70112205 0.14711004]
   [0.2958058  0.81218076 0.5458496 ]
   [0.29565126 0.6102391  0.8284941 ]
   [0.54780513 0.6722636  0.7162024 ]
   [0.41630036 0.5065842  0.51054204]
   [0.549

[[[[0.1956213  0.6310741  0.08036439]
   [0.1785023  0.6397605  0.09290528]
   [0.18047594 0.63978875 0.06545782]
   [0.19367239 0.68357605 0.09089596]
   [0.20451653 0.63668495 0.08419432]
   [0.26734158 0.7675044  0.6904478 ]
   [0.31286794 0.56583154 0.6111859 ]
   [0.5493541  0.5918021  0.6179327 ]
   [0.47926316 0.45384353 0.35410598]
   [0.5676844  0.3158384  0.5080186 ]
   [0.5451041  0.30186492 0.3078398 ]
   [0.68873924 0.7661648  0.18458952]
   [0.6439372  0.62032723 0.241967  ]
   [0.71895695 0.4990612  0.28382254]
   [0.7385737  0.4663726  0.32175916]
   [0.728435   0.5099219  0.11818306]
   [0.73639643 0.71512    0.28919777]]]]
[[[[0.20100228 0.5971472  0.06945564]
   [0.175325   0.6198324  0.08888686]
   [0.17760947 0.6199034  0.06143472]
   [0.19099745 0.68096083 0.10852822]
   [0.19468156 0.66086316 0.11433346]
   [0.2687845  0.7648279  0.7272244 ]
   [0.30159533 0.5741742  0.8089389 ]
   [0.54339194 0.6040541  0.522109  ]
   [0.46752113 0.45316717 0.5459639 ]
   [0.570

[[[[0.22653751 0.58898675 0.20581955]
   [0.21445802 0.59621894 0.1809572 ]
   [0.2180507  0.5910233  0.15973708]
   [0.2258111  0.660475   0.11709129]
   [0.25135607 0.6029824  0.13431501]
   [0.26064277 0.75442594 0.46161985]
   [0.31158927 0.564257   0.60946476]
   [0.5289929  0.6338439  0.43297252]
   [0.46473122 0.4543676  0.53065836]
   [0.56204134 0.3383667  0.40099302]
   [0.5496614  0.32517537 0.30138865]
   [0.56919396 0.7350867  0.22387369]
   [0.52050906 0.59630454 0.33171186]
   [0.5402686  0.5869978  0.26636422]
   [0.5452957  0.35771805 0.12297845]
   [0.5445288  0.5089381  0.0825173 ]
   [0.56197    0.34357664 0.13707766]]]]
[[[[0.30975568 0.5318701  0.06660524]
   [0.24661724 0.56736195 0.06894684]
   [0.21337257 0.57178026 0.08514611]
   [0.21318814 0.6741073  0.13830273]
   [0.23782048 0.6058213  0.11249302]
   [0.26142007 0.7537956  0.5809198 ]
   [0.3027835  0.55802166 0.60092527]
   [0.532871   0.63604933 0.57642806]
   [0.463968   0.45527372 0.54635   ]
   [0.563

[[[[0.19692487 0.49573863 0.03752273]
   [0.16532168 0.51558125 0.04622783]
   [0.17045218 0.5024924  0.03006034]
   [0.1864203  0.62214744 0.09632438]
   [0.19142807 0.6147073  0.12665099]
   [0.2606383  0.7434455  0.70364577]
   [0.2969075  0.5546694  0.7274848 ]
   [0.54452455 0.6060651  0.54675776]
   [0.469261   0.4459865  0.44849977]
   [0.5684607  0.32758057 0.43461788]
   [0.547266   0.3191386  0.23065124]
   [0.6590924  0.7495362  0.27412945]
   [0.612671   0.6007825  0.3456536 ]
   [0.743071   0.49240088 0.21195522]
   [0.55488944 0.3479824  0.13978516]
   [0.7460041  0.54823345 0.10952497]
   [0.7513827  0.48836228 0.1015559 ]]]]
[[[[0.1977185  0.48760444 0.03095818]
   [0.16424397 0.53363144 0.04107924]
   [0.15924513 0.5505545  0.04853911]
   [0.18660021 0.62424874 0.09099276]
   [0.19153681 0.61566615 0.13488366]
   [0.2603435  0.74422276 0.7074479 ]
   [0.29783428 0.5573458  0.7722023 ]
   [0.5432788  0.6057894  0.5565525 ]
   [0.47263408 0.44335175 0.4684805 ]
   [0.567

[[[[0.21266328 0.49786255 0.04152508]
   [0.1640969  0.5361321  0.04520567]
   [0.17909205 0.5008582  0.02268602]
   [0.18689066 0.6281805  0.08270314]
   [0.20177725 0.5890631  0.0988251 ]
   [0.25670537 0.7438971  0.78229797]
   [0.29327047 0.55740434 0.65466774]
   [0.5454033  0.6043649  0.6840999 ]
   [0.46466935 0.45142588 0.60399044]
   [0.5668279  0.33122015 0.46559298]
   [0.5449165  0.31807142 0.27588883]
   [0.6372731  0.74215096 0.27604547]
   [0.5965406  0.59781677 0.40042874]
   [0.7452035  0.5078318  0.22315979]
   [0.5547445  0.3480459  0.1332269 ]
   [0.7294475  0.6291402  0.1530236 ]
   [0.7469114  0.5223815  0.11801607]]]]
[[[[0.21318772 0.49753708 0.04331127]
   [0.16409549 0.5362861  0.04612003]
   [0.17951217 0.50024056 0.02271602]
   [0.18663518 0.6283071  0.07947412]
   [0.20134543 0.58777964 0.10588346]
   [0.2566045  0.74402803 0.76940405]
   [0.29145175 0.5542344  0.6155921 ]
   [0.5450891  0.60714424 0.6847974 ]
   [0.4648969  0.44656643 0.5322213 ]
   [0.566

[[[[0.19851485 0.5066632  0.03849566]
   [0.16810922 0.5394641  0.05193951]
   [0.17100453 0.54150856 0.0418001 ]
   [0.18683922 0.64319134 0.09039111]
   [0.19292454 0.61776394 0.12328938]
   [0.26007137 0.74546206 0.71144694]
   [0.30351037 0.558033   0.7206864 ]
   [0.5407864  0.60892403 0.53332496]
   [0.47614437 0.45210153 0.4405658 ]
   [0.559059   0.3241734  0.53162795]
   [0.5466937  0.32042855 0.33431813]
   [0.6593989  0.7452845  0.2954161 ]
   [0.6331705  0.6038152  0.32642108]
   [0.7453224  0.5046427  0.22673093]
   [0.7525548  0.48210227 0.30244687]
   [0.73560727 0.73569286 0.3048627 ]
   [0.7464495  0.52050716 0.10349344]]]]
[[[[0.19845377 0.50668186 0.03869162]
   [0.16714357 0.5399262  0.04821737]
   [0.16976319 0.54299825 0.03637131]
   [0.18671101 0.6428423  0.08703498]
   [0.20110095 0.5943428  0.08444828]
   [0.26214984 0.7471997  0.7385199 ]
   [0.301119   0.56143653 0.6968828 ]
   [0.54124486 0.60811746 0.5850192 ]
   [0.46963406 0.4516527  0.5341628 ]
   [0.566

[[[[0.19781023 0.54995954 0.05210001]
   [0.16439474 0.55663073 0.04879291]
   [0.1708781  0.5216632  0.0325954 ]
   [0.18299375 0.66361105 0.07576551]
   [0.20052503 0.5942635  0.08335022]
   [0.26085538 0.7468873  0.6720516 ]
   [0.29440907 0.56424105 0.61041087]
   [0.54792213 0.60882455 0.6526567 ]
   [0.4702844  0.45238912 0.5268928 ]
   [0.5589545  0.31686363 0.50888616]
   [0.5456121  0.30647367 0.31401306]
   [0.65742576 0.73741686 0.26027432]
   [0.61424255 0.60123074 0.33262143]
   [0.6953552  0.56694245 0.32732016]
   [0.5554827  0.35113785 0.10646766]
   [0.7086243  0.58755517 0.11496648]
   [0.7490856  0.5046165  0.08678383]]]]
[[[[0.21687923 0.5136324  0.04531114]
   [0.17395425 0.55308616 0.03519749]
   [0.19320232 0.4999711  0.03696275]
   [0.1842022  0.64701235 0.06861668]
   [0.20044878 0.5916928  0.08924753]
   [0.26040578 0.7471003  0.6724166 ]
   [0.29357693 0.5606603  0.6044508 ]
   [0.54722565 0.61218965 0.6256502 ]
   [0.46825206 0.44985414 0.5126516 ]
   [0.568

[[[[0.1996173  0.56298864 0.08263139]
   [0.16835076 0.55595905 0.06124346]
   [0.18316254 0.5197144  0.02937345]
   [0.1856159  0.64625055 0.07962535]
   [0.20100364 0.5944614  0.08853406]
   [0.2616774  0.7480268  0.6696599 ]
   [0.29067057 0.56507015 0.5979407 ]
   [0.54364336 0.61396265 0.7364405 ]
   [0.46082598 0.45918712 0.5707899 ]
   [0.5668101  0.3292418  0.45076445]
   [0.5447862  0.31626865 0.2536419 ]
   [0.61497915 0.73256564 0.28811413]
   [0.5703727  0.5969506  0.40862247]
   [0.6797968  0.58198774 0.43707785]
   [0.5569993  0.34999985 0.11953496]
   [0.71548784 0.5915407  0.12490982]
   [0.69681275 0.5826516  0.16756953]]]]
[[[[0.19942844 0.5148556  0.03734751]
   [0.16575122 0.552568   0.05302593]
   [0.17052683 0.51859766 0.03273023]
   [0.1849364  0.6437474  0.08472853]
   [0.20036796 0.5930681  0.08558033]
   [0.26058573 0.7461197  0.6889877 ]
   [0.2941653  0.563679   0.6731256 ]
   [0.54337794 0.6178462  0.7126201 ]
   [0.4650912  0.45533657 0.55263084]
   [0.567

[[[[0.20075326 0.51784873 0.03617326]
   [0.16945063 0.5527725  0.05608596]
   [0.17401454 0.5231789  0.033492  ]
   [0.18547353 0.65667415 0.10814415]
   [0.19266449 0.6208671  0.11209862]
   [0.25980464 0.74655384 0.70667166]
   [0.2950627  0.5627981  0.72368664]
   [0.54123616 0.61445725 0.5830805 ]
   [0.4668276  0.4546226  0.5971683 ]
   [0.5685579  0.32236654 0.611717  ]
   [0.54518163 0.31700063 0.25242597]
   [0.65554285 0.7435095  0.33212605]
   [0.61244243 0.6152767  0.45803222]
   [0.7499859  0.5040141  0.20995012]
   [0.7550788  0.4794719  0.31780788]
   [0.7353337  0.73353374 0.36961767]
   [0.75252557 0.50528586 0.07457194]]]]
[[[[0.19820637 0.5193111  0.03257148]
   [0.16932932 0.5387691  0.05032669]
   [0.17224738 0.52570623 0.02804008]
   [0.18685846 0.6417383  0.09319612]
   [0.19289063 0.62063944 0.11198089]
   [0.2605048  0.7468667  0.7188815 ]
   [0.29715395 0.5610472  0.7540228 ]
   [0.54149663 0.6140622  0.6017055 ]
   [0.4699007  0.4517016  0.46896327]
   [0.568

[[[[0.19660465 0.5607522  0.04762373]
   [0.16563839 0.5603763  0.03950956]
   [0.16741544 0.5464866  0.02657335]
   [0.18534598 0.6612848  0.09476779]
   [0.19916084 0.6109378  0.07939068]
   [0.26007393 0.7503025  0.67609906]
   [0.3014627  0.56112665 0.75986767]
   [0.54131734 0.6132592  0.60444176]
   [0.47254765 0.44871688 0.44463977]
   [0.56677115 0.32436755 0.6318688 ]
   [0.5462798  0.30802336 0.33522695]
   [0.66521084 0.7431927  0.33418822]
   [0.6405803  0.6018442  0.40968218]
   [0.7409818  0.5306307  0.1912327 ]
   [0.7565729  0.47476766 0.32368478]
   [0.73358893 0.73946184 0.23205882]
   [0.7530967  0.50090927 0.08144671]]]]
[[[[0.20206508 0.564698   0.08030804]
   [0.17743465 0.57783854 0.08782426]
   [0.18070826 0.57921237 0.06549551]
   [0.19196604 0.6580783  0.11184333]
   [0.20637688 0.61127293 0.09864908]
   [0.2575947  0.749192   0.6319964 ]
   [0.30363098 0.5648192  0.6386289 ]
   [0.54391646 0.6101563  0.74712014]
   [0.4711554  0.4475678  0.4097881 ]
   [0.566

[[[[0.21590304 0.51303816 0.0422185 ]
   [0.1699611  0.53539485 0.05312802]
   [0.19020805 0.51845354 0.02506461]
   [0.18964861 0.64120054 0.08919267]
   [0.20394054 0.6074189  0.09852394]
   [0.25875163 0.74828994 0.63535154]
   [0.29925275 0.5591285  0.6743142 ]
   [0.54782474 0.6121836  0.6120527 ]
   [0.46977127 0.44808993 0.45735145]
   [0.5576067  0.3245195  0.55574256]
   [0.548612   0.31638116 0.37953967]
   [0.64456    0.7477142  0.2757989 ]
   [0.61674607 0.6151525  0.47613114]
   [0.6904287  0.5770447  0.4351917 ]
   [0.7542252  0.4770229  0.3834623 ]
   [0.7102882  0.5923792  0.11342033]
   [0.7485769  0.501391   0.10346288]]]]
[[[[0.21484634 0.5096389  0.04384425]
   [0.16718712 0.53273916 0.04488456]
   [0.19024071 0.5003553  0.02015766]
   [0.1869691  0.6408997  0.08547722]
   [0.20153503 0.60785145 0.09437193]
   [0.25858665 0.7460971  0.64032704]
   [0.29790795 0.56121814 0.6740999 ]
   [0.5441368  0.6122499  0.7122829 ]
   [0.46704012 0.44976616 0.4585081 ]
   [0.557

[[[[0.20277952 0.47600752 0.10385795]
   [0.17254508 0.4913492  0.09508286]
   [0.18878077 0.47693703 0.06067233]
   [0.1885935  0.59283453 0.12728952]
   [0.19966096 0.5267992  0.09460441]
   [0.25777107 0.72491324 0.59532547]
   [0.3129359  0.53713155 0.5497101 ]
   [0.5399203  0.6126944  0.45800695]
   [0.47206074 0.44456524 0.3779125 ]
   [0.5624539  0.32400012 0.4953581 ]
   [0.55091053 0.31174868 0.2698101 ]
   [0.6579892  0.73745644 0.14016707]
   [0.6120309  0.62482274 0.19954564]
   [0.65236276 0.49301922 0.05562446]
   [0.5521642  0.34986335 0.11464689]
   [0.74043024 0.507278   0.05739176]
   [0.70182246 0.39062017 0.02106874]]]]
[[[[0.21984218 0.48241657 0.10249677]
   [0.19540238 0.48189563 0.07468656]
   [0.20064837 0.47793517 0.08447957]
   [0.2134785  0.5939536  0.10277898]
   [0.21938293 0.5114339  0.06841235]
   [0.25326174 0.72090375 0.5349443 ]
   [0.3195382  0.53730494 0.48077732]
   [0.5444247  0.6071584  0.4412555 ]
   [0.47127998 0.44470358 0.36067307]
   [0.560

[[[[0.21810856 0.46956202 0.08511746]
   [0.17633341 0.48997396 0.06413402]
   [0.20513152 0.47196597 0.04263882]
   [0.2032938  0.5821394  0.0924448 ]
   [0.20752108 0.571963   0.17280805]
   [0.2598535  0.72047067 0.61311734]
   [0.31653306 0.536327   0.5421951 ]
   [0.54192257 0.6083636  0.5448569 ]
   [0.4799705  0.44562346 0.35065883]
   [0.563472   0.3264477  0.5264763 ]
   [0.5510859  0.31168106 0.30033705]
   [0.6135559  0.74712276 0.14004025]
   [0.58024406 0.6113149  0.14077072]
   [0.7218985  0.48464924 0.0715699 ]
   [0.55217016 0.34666622 0.11134575]
   [0.7431418  0.51297903 0.04674461]
   [0.7363186  0.4563508  0.02400908]]]]
[[[[0.215305   0.46707386 0.08460479]
   [0.17244242 0.48922786 0.06774801]
   [0.19000146 0.47150514 0.03916342]
   [0.19015884 0.5905398  0.11293937]
   [0.20116445 0.5649624  0.15628941]
   [0.25924203 0.71808594 0.7368704 ]
   [0.315021   0.53529185 0.5602488 ]
   [0.5434662  0.609596   0.56996644]
   [0.50139177 0.44695503 0.2000461 ]
   [0.563

[[[[0.23815677 0.500202   0.05734414]
   [0.23970228 0.54702365 0.04488022]
   [0.22550848 0.49363798 0.02178126]
   [0.19037226 0.6548301  0.10259157]
   [0.21534353 0.600531   0.10490163]
   [0.26154122 0.7376449  0.5705768 ]
   [0.29844004 0.5574011  0.6717438 ]
   [0.54173297 0.60845983 0.58057624]
   [0.4713536  0.44722113 0.37039778]
   [0.55862164 0.33431947 0.5332482 ]
   [0.5454287  0.32023442 0.3305261 ]
   [0.61403215 0.6979853  0.18941434]
   [0.5657724  0.554484   0.20888542]
   [0.5685394  0.36320412 0.13126981]
   [0.55737853 0.30547407 0.08306638]
   [0.730641   0.4198411  0.03787814]
   [0.5619376  0.32431775 0.06627402]]]]
[[[[0.31530407 0.49443793 0.05456427]
   [0.24470353 0.5185609  0.02821663]
   [0.23118496 0.5057155  0.03373654]
   [0.21074986 0.65564036 0.07590219]
   [0.21744266 0.5987439  0.11070392]
   [0.2634333  0.73713243 0.5580168 ]
   [0.2978349  0.55542624 0.6409192 ]
   [0.54133534 0.60779774 0.5825502 ]
   [0.47147283 0.44513524 0.35785913]
   [0.558

[[[[0.22855823 0.5124283  0.03334306]
   [0.19047324 0.55739725 0.05232455]
   [0.18070589 0.55477583 0.0526605 ]
   [0.20322226 0.64174116 0.07531194]
   [0.20803694 0.62017584 0.12493701]
   [0.25646296 0.7337214  0.67010957]
   [0.2907238  0.5664741  0.6061187 ]
   [0.53966    0.60888934 0.65071386]
   [0.46406326 0.44658384 0.5298749 ]
   [0.56281406 0.33715114 0.4554237 ]
   [0.5443893  0.32241595 0.24674843]
   [0.59320116 0.69502854 0.25906563]
   [0.5599392  0.57217205 0.25118285]
   [0.55632174 0.37831467 0.1842701 ]
   [0.5522989  0.3281852  0.10457665]
   [0.73819745 0.47285533 0.06938354]
   [0.562641   0.3269893  0.0955582 ]]]]
[[[[0.20127454 0.5503872  0.05989938]
   [0.1861726  0.5592582  0.04280467]
   [0.18882623 0.5588999  0.0404008 ]
   [0.20141155 0.64142704 0.06789739]
   [0.20586883 0.6188944  0.11522708]
   [0.25726193 0.7350285  0.5561767 ]
   [0.2949083  0.56445926 0.6596501 ]
   [0.54057926 0.6122682  0.5729378 ]
   [0.46816766 0.44855377 0.5696478 ]
   [0.563

[[[[0.18530816 0.19103901 0.03720631]
   [0.15598524 0.1928547  0.04165535]
   [0.15925759 0.17625192 0.04710291]
   [0.17740005 0.28687257 0.09644274]
   [0.19329266 0.18666053 0.08088746]
   [0.26441804 0.3809553  0.7157475 ]
   [0.30983648 0.14151323 0.75096995]
   [0.5743123  0.27180594 0.5555633 ]
   [0.50483036 0.0259029  0.265095  ]
   [0.6560444  0.02554252 0.11506858]
   [0.6586297  0.01822177 0.0704863 ]
   [0.70940757 0.31394115 0.09855039]
   [0.68158853 0.12647088 0.11065849]
   [0.7240925  0.25756904 0.04533484]
   [0.6781064  0.01186031 0.03958807]
   [0.73458433 0.31227422 0.09351235]
   [0.72600985 0.13185829 0.01930779]]]]
[[[[0.18273655 0.17488694 0.03477522]
   [0.15209232 0.17620353 0.04366361]
   [0.1549901  0.16124927 0.03836237]
   [0.17358908 0.28302568 0.0932204 ]
   [0.18655007 0.17947301 0.08551878]
   [0.25772542 0.3739042  0.62356585]
   [0.30916575 0.11617528 0.79770947]
   [0.5798483  0.25928196 0.5445467 ]
   [0.48652768 0.01672702 0.25924912]
   [0.649

[[[[ 0.05320899  0.0089251   0.09531866]
   [ 0.02881882  0.00978519  0.08756394]
   [ 0.02709573  0.00287215  0.07629137]
   [ 0.21086882  0.02137242  0.08155257]
   [ 0.16865395 -0.00550472  0.03823485]
   [ 0.25582907  0.26668903  0.38669136]
   [ 0.30512026  0.01512277  0.08847132]
   [ 0.64608824  0.2940007   0.10097867]
   [ 0.618162    0.18629967  0.16718245]
   [ 0.6943661   0.39572573  0.07995274]
   [ 0.68488586  0.37947196  0.07663186]
   [ 0.68690145  0.3823254   0.05606892]
   [ 0.75281423  0.19930105  0.05044937]
   [ 0.578942    0.84154576  0.03364215]
   [ 0.66472024  0.5814059   0.01483447]
   [ 0.5922683   0.83833134  0.04080471]
   [ 0.6098937   0.8413782   0.01957335]]]]
[[[[0.0530543  0.00991113 0.10293776]
   [0.02813141 0.01069099 0.09431957]
   [0.026326   0.00393983 0.08469117]
   [0.04472297 0.02441699 0.09971219]
   [0.1486105  0.01381285 0.02770388]
   [0.26057255 0.2751552  0.40161452]
   [0.30998427 0.00623445 0.06911649]
   [0.68814725 0.39440438 0.103142

[[[[0.05943676 0.01272509 0.09372617]
   [0.02988268 0.01071323 0.08933672]
   [0.02806379 0.00287055 0.07544105]
   [0.04496486 0.02387786 0.09445627]
   [0.10468508 0.13579443 0.0136693 ]
   [0.25259748 0.2788896  0.44889143]
   [0.25081962 0.10897541 0.03223916]
   [0.67862695 0.48222816 0.07365999]
   [0.61106783 0.19550465 0.17102331]
   [0.7140964  0.5251566  0.02697693]
   [0.6952638  0.49245125 0.05247993]
   [0.744295   0.4329344  0.05587804]
   [0.7669698  0.28571588 0.04317063]
   [0.73686403 0.8122935  0.03014889]
   [0.721147   0.48848242 0.01251224]
   [0.70521235 0.83523273 0.01413625]
   [0.75965667 0.96950215 0.02438156]]]]
[[[[0.05961695 0.01296344 0.09893343]
   [0.02967985 0.01097902 0.09213332]
   [0.02797157 0.00313392 0.07822895]
   [0.04526203 0.0246814  0.10438947]
   [0.10775649 0.07172116 0.02049273]
   [0.25481153 0.27946544 0.47160122]
   [0.27831492 0.04962301 0.04681786]
   [0.58887243 0.61181957 0.13960342]
   [0.60800916 0.19430554 0.1511992 ]
   [0.752

[[[[0.44593462 0.5079062  0.02117855]
   [0.3713131  0.5355331  0.01287392]
   [0.37258157 0.47741422 0.01667999]
   [0.58878124 0.543969   0.07556277]
   [0.5720579  0.50766015 0.09874156]
   [0.4306824  0.6285361  0.02903526]
   [0.48280916 0.3953429  0.08205547]
   [0.64954823 0.707904   0.02740308]
   [0.5982862  0.32629472 0.23498721]
   [0.69873756 0.66848105 0.03077893]
   [0.74560803 0.45297727 0.07922657]
   [0.64063686 0.6201475  0.0379071 ]
   [0.6380125  0.50024426 0.03977358]
   [0.5980089  0.5060062  0.05187315]
   [0.605514   0.5119513  0.07153216]
   [0.66149926 0.49220523 0.04006911]
   [0.6544399  0.5468732  0.05945345]]]]
[[[[0.5773781  0.4331289  0.06739199]
   [0.6360776  0.4811982  0.10047248]
   [0.63460785 0.25801587 0.090814  ]
   [0.6192459  0.55508524 0.13613111]
   [0.72158927 0.30051598 0.12665004]
   [0.6195865  0.6154816  0.07917961]
   [0.5776183  0.30356276 0.07412625]
   [0.60507596 0.76700896 0.06710853]
   [0.6350526  0.25635532 0.17348056]
   [0.608

[[[[0.13836373 0.54031146 0.03199099]
   [0.05001994 0.59718907 0.01977214]
   [0.02958305 0.46026978 0.01435381]
   [0.05315426 0.69782704 0.01241721]
   [0.01784231 0.36793864 0.03373756]
   [0.22395764 0.8653333  0.02593081]
   [0.20175788 0.27544677 0.35269368]
   [0.6552676  0.9217455  0.08643939]
   [0.5658353  0.22017477 0.41426164]
   [0.6553425  0.91841173 0.14041683]
   [0.70200413 0.12867425 0.18544255]
   [0.7873739  0.7396611  0.12751399]
   [0.7813132  0.39219663 0.17643979]
   [0.75422925 0.7035153  0.00942845]
   [0.74191165 0.02923492 0.05473984]
   [0.75737417 0.52460396 0.00814569]
   [0.7442167  0.40863508 0.04514554]]]]
[[[[0.15691017 0.56041336 0.02653747]
   [0.07150258 0.6166475  0.01612079]
   [0.05216063 0.48145065 0.01329465]
   [0.05875206 0.70252913 0.01333892]
   [0.02006189 0.37155244 0.03065165]
   [0.21425687 0.8822433  0.03559202]
   [0.20394658 0.2794341  0.3052285 ]
   [0.66555667 0.9298372  0.1030607 ]
   [0.566966   0.22192912 0.4598627 ]
   [0.656

[[[[0.23655811 0.44776613 0.08404034]
   [0.24131952 0.49019742 0.02560669]
   [0.23387834 0.38042706 0.01722864]
   [0.1897912  0.6244372  0.00738524]
   [0.18330348 0.3269301  0.06002874]
   [0.22994553 0.506463   0.09820771]
   [0.24088162 0.28950065 0.45705876]
   [0.6585541  0.77508634 0.03987576]
   [0.650471   0.18868682 0.22588271]
   [0.7454784  0.9146179  0.04811381]
   [0.7846159  0.07849391 0.23638584]
   [0.7390148  0.6080945  0.04625664]
   [0.7323837  0.2751898  0.0911184 ]
   [0.6397942  0.5631106  0.0235836 ]
   [0.6130345  0.24436331 0.03414507]
   [0.73765033 0.3852963  0.03023418]
   [0.7412405  0.37093362 0.03316143]]]]
[[[[0.22367507 0.4457862  0.05788155]
   [0.1873433  0.49247712 0.02069072]
   [0.16706799 0.38267267 0.01454573]
   [0.1423127  0.59663856 0.00564117]
   [0.1531156  0.33227274 0.03953502]
   [0.22981262 0.75965214 0.03418786]
   [0.23889022 0.28916752 0.4857496 ]
   [0.64074767 0.8183973  0.05085536]
   [0.5978549  0.22300586 0.32693288]
   [0.776

[[[[0.2517572  0.6264186  0.20041823]
   [0.2321054  0.6665377  0.12323081]
   [0.22012246 0.60516167 0.14040865]
   [0.28499746 0.7646314  0.12922189]
   [0.2730895  0.5436383  0.20720924]
   [0.53927076 0.922904   0.6802003 ]
   [0.5511743  0.33447915 0.8473964 ]
   [0.74453783 0.97907966 0.04920112]
   [0.75888646 0.2718215  0.06944168]
   [0.54492134 0.7478657  0.00827906]
   [0.38594437 0.6002867  0.02756388]
   [0.7736871  0.96988386 0.01525431]
   [0.1847249  0.724684   0.02018667]
   [0.5347183  0.9509696  0.02450057]
   [0.5718093  0.3410269  0.02645985]
   [0.36182272 0.646023   0.01815831]
   [0.35941753 0.609017   0.02358915]]]]
[[[[0.31782436 0.62884986 0.14259923]
   [0.26550135 0.6871362  0.13737743]
   [0.25943762 0.6059259  0.16467734]
   [0.30012435 0.76946354 0.11976103]
   [0.30115706 0.51954556 0.12721838]
   [0.56300384 0.9287433  0.6709728 ]
   [0.5775627  0.33684802 0.8581877 ]
   [0.7423146  0.97470486 0.05185463]
   [0.75238264 0.28034955 0.08193347]
   [0.533

[[[[0.29785496 0.5879291  0.3418188 ]
   [0.2584701  0.6299691  0.26645252]
   [0.26221025 0.548592   0.22512548]
   [0.2923072  0.6964511  0.1736566 ]
   [0.2944806  0.50400245 0.34157622]
   [0.5779439  0.8493674  0.53600836]
   [0.594756   0.32917303 0.8867553 ]
   [0.76131094 0.96141833 0.07807936]
   [0.64315426 0.29871127 0.01417724]
   [0.4475051  0.73589635 0.01165454]
   [0.51192147 0.47921687 0.01428228]
   [0.79333115 0.93546844 0.01433126]
   [0.78868675 0.93457836 0.01321638]
   [0.585173   0.89846647 0.03216183]
   [0.61317986 0.31121564 0.01237591]
   [0.5543169  0.87265205 0.01120324]
   [0.3830877  0.60508364 0.00905909]]]]
[[[[0.29939678 0.58797145 0.45726424]
   [0.2590354  0.63043165 0.34091163]
   [0.26285657 0.54564214 0.27441132]
   [0.29653227 0.6978899  0.26180053]
   [0.30395907 0.49398237 0.36999744]
   [0.5815283  0.8677478  0.60845983]
   [0.59427637 0.327946   0.6721002 ]
   [0.76379126 0.9613783  0.08055824]
   [0.6211039  0.30480045 0.02084453]
   [0.475

[[[[0.32510233 0.58107257 0.20567517]
   [0.26987734 0.6305019  0.17560972]
   [0.26049882 0.53841245 0.21567751]
   [0.30413598 0.6875372  0.21763012]
   [0.3154959  0.47885245 0.3994094 ]
   [0.59153235 0.87385696 0.43951246]
   [0.5939051  0.31794783 0.81455946]
   [0.7486191  0.9639056  0.0947172 ]
   [0.7365086  0.26355332 0.02310869]
   [0.45994732 0.73298633 0.01012547]
   [0.5016345  0.46766683 0.02011825]
   [0.78724957 0.94379103 0.02001138]
   [0.79273593 0.93640774 0.02020784]
   [0.6223968  0.9542388  0.02791737]
   [0.59403217 0.3047705  0.01147225]
   [0.5556061  0.8728807  0.01441164]
   [0.60142106 0.01990183 0.01702505]]]]
[[[[0.31509227 0.5877323  0.27595976]
   [0.27382168 0.6396935  0.1288351 ]
   [0.27346268 0.5425111  0.12283628]
   [0.30118757 0.68839073 0.24125741]
   [0.3132949  0.48313627 0.3679105 ]
   [0.58640265 0.88071084 0.6284263 ]
   [0.5908417  0.32021776 0.80001205]
   [0.74968904 0.9630124  0.09001482]
   [0.73350394 0.2635327  0.02187187]
   [0.514

In [7]:
right_eye = keypoints_with_scores[0][0][2]
left_elbow = keypoints_with_scores[0][0][7] 
#where acutally your left elbow is in the frame in pixels  
#left_elbow[:2]*[480,640]   #*actual frame을 곱해야해
np.array(left_elbow[:2]*[480,640]).astype(int) #pixel coordinates

array([436, 623])

In [3]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape   #y coord, x coord, channel coordinates
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1])) #multiply our frame shape를 해줘서 실제 좌표값 confidence는 transform 해주기 싫으니 1 곱하구
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx),int(ky)), 4, (0,255,0), -1)

In [4]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}


In [5]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)

